#ifndef HHS_PASS159_AST_H
#define HHS_PASS159_AST_H
#include "hhs_pass159_types.h"
typedef enum {
    HHS159_NODE_PROGRAM = 1,
    HHS159_NODE_MODULE,
    HHS159_NODE_DECLARATION,
    HHS159_NODE_CHAIN_EQUALITY,
    HHS159_NODE_ASSERTION_EQUALITY,
    HHS159_NODE_ORDERED_DISTINCTNESS,
    HHS159_NODE_ORDERED_PRODUCT,
    HHS159_NODE_MODULAR_EXPRESSION,
    HHS159_NODE_LIST_EXPRESSION,
    HHS159_NODE_TENSOR_EXPRESSION,
    HHS159_NODE_CALL_EXPRESSION,
    HHS159_NODE_TRANSITION_EXPRESSION,
    HHS159_NODE_RAW_NATIVE_EXPRESSION
} HHS159NodeKind;
#endif
