import HHS.Mathlib.Native

namespace HHS.Mathlib.OrderRat

/-- Exact rational proof representation.
The denominator is positive; no floating-point projection is part of the type. -/
structure ExactRat where
  numerator : Int
  denominator : Nat
  denominatorPos : 0 < denominator

/-- Rational equivalence without requiring canonical GCD reduction. -/
def ExactRat.eqv (a b : ExactRat) : Prop :=
  a.numerator * Int.ofNat b.denominator =
    b.numerator * Int.ofNat a.denominator

theorem ExactRat.eqv_refl (q : ExactRat) : q.eqv q := by
  rfl

/-- Strict order for positive-denominator exact rational pairs. -/
def ExactRat.lt (a b : ExactRat) : Prop :=
  a.numerator * Int.ofNat b.denominator <
    b.numerator * Int.ofNat a.denominator

/-- Non-strict order is strict order or exact rational equivalence. -/
def ExactRat.le (a b : ExactRat) : Prop :=
  a.lt b ∨ a.eqv b

theorem ExactRat.le_refl (q : ExactRat) : q.le q := by
  exact Or.inr (ExactRat.eqv_refl q)

theorem ExactRat.lt_irrefl_native (q : ExactRat) : ¬ q.lt q := by
  intro h
  exact Int.lt_irrefl _ h

/-- Runtime comparison result generated by Python1-backed C++ cross-products. -/
inductive Relation
  | less
  | equal
  | greater
deriving Repr, BEq, DecidableEq

/-- Receipt for one exact rational/order runtime decision. -/
structure RelationWitness where
  relation : Relation
  python1Executed : Bool
  positiveDenominators : Bool
  crossProductComparison : Bool
  hostFloatUsed : Bool
  hostIntegerComparisonUsed : Bool
deriving Repr, BEq, DecidableEq

def RelationWitness.admitted (w : RelationWitness) : Prop :=
  w.python1Executed = true ∧
  w.positiveDenominators = true ∧
  w.crossProductComparison = true ∧
  w.hostFloatUsed = false ∧
  w.hostIntegerComparisonUsed = false

theorem relation_admission_requires_python1
    (w : RelationWitness)
    (h : w.admitted) :
    w.python1Executed = true :=
  h.1

theorem relation_admission_forbids_host_float
    (w : RelationWitness)
    (h : w.admitted) :
    w.hostFloatUsed = false :=
  h.2.2.2.1

/-- I049 remains an exact bounded pair representation, not a completeness claim. -/
def gcdReductionRequiredForIdentity : Bool := false

theorem exact_pair_identity_does_not_require_gcd_reduction :
    gcdReductionRequiredForIdentity = false := by
  rfl

end HHS.Mathlib.OrderRat
