"""Parse source-bound *diagnostic* native receipt and reject unearned authority.

This is a gate-evidence inventory, not a witness producer. All 40 truth
values deliberately remain UNRESOLVED until independently proven by the
canonical shared-environment VM81 layer.
"""
from __future__ import annotations
from hashlib import sha256
from pathlib import Path
import re

SOURCE = Path("contracts/pass220/PASS_220_ORDERED_PHASE_CHAIN_V4_20261009.harmonicode")
ARTIFACT = Path("artifacts/pass220/v4-source-general/replay_preflight.txt")


def gate_offsets(data: bytes) -> list[tuple[int, int]]:
    depth = 0
    observed = []
    i = 0
    while i < len(data):
        b = data[i]
        if b == ord("("):
            depth += 1
        elif b == ord(")"):
            depth -= 1
            assert depth >= 0
        elif b == ord("=") and data[i:i+2] == b"==":
            observed.append((i, depth))
            i += 1
        i += 1
    assert depth == 0
    return observed


def test_exact_inherited_source_has_40_distinct_positioned_occurrences() -> None:
    data = SOURCE.read_bytes()
    assert len(data) == 527
    assert data.endswith(b"\n")
    offsets = gate_offsets(data)
    assert len(offsets) == 40
    assert len({o for o, _ in offsets}) == 40
    assert [o for o,d in offsets if d == 0] == [253,256]
    assert data.count(b"u^72==x*y") == 1
    assert data.count(b"u^36==(y*x*w*z)/a^2") == 1
    assert data.count(b"==x==-y*(") == 1


def test_synthetic_true_gate_manifest_does_not_substitute_proof() -> None:
    data = SOURCE.read_bytes()
    offsets = gate_offsets(data)
    unproved = [{"gate_index":i, "byte_offset":pos, "depth":depth,
                 "source_sha256":sha256(data).hexdigest(),
                 "proof":None} for i,(pos,depth) in enumerate(offsets)]
    assert len(unproved) == 40
    assert all(item["proof"] is None for item in unproved)
    assert not all(item["proof"] is True for item in unproved)
    # Any source mutation requires fresh evidence; no older source-root inheritance.
    modified = data.replace(b"==x==-y*(",b"==-y==x*(",1)
    assert modified != data
    assert sha256(modified).digest() != sha256(data).digest()


def test_native_hold_replay_and_compiler_evidence_not_canonical_commit() -> None:
    if not ARTIFACT.is_file():
        # Checked in the dedicated CI job after the probe is executed.
        import pytest
        pytest.skip("Native replay-preflight artifact generated by CI")
    text = ARTIFACT.read_text(encoding="ascii")
    data = SOURCE.read_bytes()
    assert "source_sha256="+sha256(data).hexdigest() in text
    assert "source_bytes=527" in text
    assert "gate_occurrences=40" in text
    lines = re.findall(r"^gate_(\d\d)_offset=(\d+);depth=(\d+);truth=(\w+)$",text,re.M)
    offsets = gate_offsets(data)
    assert len(lines) == 40
    for index,(row,(pos,depth)) in enumerate(zip(lines,offsets)):
        assert tuple(row) == (f"{index:02d}", str(pos), str(depth), "UNRESOLVED")
    for evidence in (
        "hold_status=0", "replay_status=0", "replay_semantic_root_equal=1",
        "interpreter_compiler_status=0","interpreter_compiler_match=1",
        "native_hold_committed=0","canonical_vm81_admission_verified=0",
        "all_40_gate_truth_witnesses_verified=0",
        "global_gate_proof_status=UNRESOLVED","native_source_preflight=PASS"
    ):
        assert evidence in text,evidence
    assert re.search(r"^hold_vm81_steps=[1-9][0-9]*$",text,re.M)
    for name in ("source_hash216","hold_receipt_hash216","replay_receipt_hash216"):
        found = re.search(r"^"+name+r"=(.+)$",text,re.M)
        assert found and len(found.group(1)) == 216
