from __future__ import annotations

import asyncio

import pytest

from hhs_backend.runtime.hhs_assistant_api_tool_gateway_v1 import DEFAULT_HHS_ASSISTANT_TOOLS
from hhs_backend.runtime.hhs_native_litert_lm_provider_v1 import HHSNativeLiteRTLMTransport
from hhs_backend.runtime.hhs_pass220_native_causal_lm_generation_v1 import (
    NativeCausalLMGenerationError,
    NativeCausalLMGenerationService,
    NativeCausalLMNotReady,
)


class FakeTokenizer:
    name_or_path = "fake-tokenizer"

    def __init__(self) -> None:
        self.prompts = []

    def apply_chat_template(self, messages, tokenize=False, add_generation_prompt=False):
        assert tokenize is False
        assert add_generation_prompt is True
        return "\n".join(f"{item['role']}::{item['content']}" for item in messages) + "\nassistant::"

    def __call__(self, prompt, return_tensors="pt", truncation=False):
        assert return_tensors == "pt"
        assert truncation is False
        self.prompts.append(prompt)
        return {"input_ids": [[1, 2, 3, 4]]}

    def decode(self, token_ids, skip_special_tokens=True):
        assert skip_special_tokens is True
        assert list(token_ids) == [9, 10, 11]
        return "Native causal response."


class FakeModel:
    name_or_path = "fake-causal-model"

    def generate(self, **kwargs):
        assert kwargs["input_ids"] == [[1, 2, 3, 4]]
        assert kwargs["do_sample"] is False
        assert kwargs["max_new_tokens"] == 64
        return [[1, 2, 3, 4, 9, 10, 11]]


class PrefixMismatchModel:
    name_or_path = "fake-prefix-mismatch"

    def generate(self, **kwargs):
        return [[1, 2, 99, 9]]


class FakeWord2Vec:
    def status(self):
        return {
            "offline_ready": True,
            "active_model_id": "fake-word2vec",
            "installed_models": 1,
        }

    def nearest(self, token, top_k=4):
        return {
            "model_id": "fake-word2vec",
            "approximate": False,
            "results": [
                {
                    "token": f"{token}-neighbor-{index}",
                    "score": 1,
                }
                for index in range(top_k)
            ],
        }


class FakeGenerationService:
    def __init__(self) -> None:
        self.calls = []

    def status(self):
        return {
            "configured": True,
            "loaded": True,
            "ready": True,
            "model_id": "fake-native-causal",
        }

    def generate(self, messages, *, retrieval_context=None, max_new_tokens=None):
        self.calls.append({
            "messages": [dict(item) for item in messages],
            "retrieval_context": retrieval_context,
            "max_new_tokens": max_new_tokens,
        })
        return {
            "response": "Generated by the native causal model.",
            "receipt": {
                "receipt_root_hash72": "r" * 72,
                "causal_prefix_verified": True,
                "canonical_vm81_mutation_authority": False,
            },
            "status": self.status(),
        }


def test_native_causal_generation_decodes_only_new_tokens_and_witnesses_receipt():
    tokenizer = FakeTokenizer()
    service = NativeCausalLMGenerationService(
        tokenizer=tokenizer,
        model=FakeModel(),
        model_id="fake-causal-model",
        max_new_tokens=64,
    )

    result = service.generate(
        [
            {"role": "system", "content": "governed system"},
            {"role": "user", "content": "hello"},
        ],
        retrieval_context="candidate context",
    )

    assert result["response"] == "Native causal response."
    receipt = result["receipt"]
    assert receipt["input_token_count"] == 4
    assert receipt["generated_token_count"] == 3
    assert receipt["causal_prefix_verified"] is True
    assert receipt["natural_language_egress_only"] is True
    assert receipt["canonical_vm81_mutation_authority"] is False
    assert receipt["canonical_hash72_mutation_authority"] is False
    assert receipt["canonical_hash216_mutation_authority"] is False
    assert len(receipt["receipt_root_hash72"]) == 72
    assert "Retrieved candidate context follows" in tokenizer.prompts[-1]
    assert "candidate context" in tokenizer.prompts[-1]


def test_native_causal_generation_rejects_prefix_corruption():
    service = NativeCausalLMGenerationService(
        tokenizer=FakeTokenizer(),
        model=PrefixMismatchModel(),
        max_new_tokens=64,
    )

    with pytest.raises(NativeCausalLMGenerationError, match="does not preserve"):
        service.generate([{"role": "user", "content": "hello"}])


def test_unconfigured_native_causal_service_fails_closed(monkeypatch):
    monkeypatch.delenv("HHS_NATIVE_CAUSAL_LM_MODEL", raising=False)
    service = NativeCausalLMGenerationService()

    assert service.status()["configured"] is False
    with pytest.raises(NativeCausalLMNotReady, match="not configured"):
        service.generate([{"role": "user", "content": "hello"}])


def test_native_general_chat_prefers_real_causal_generation_when_ready():
    generator = FakeGenerationService()
    provider = HHSNativeLiteRTLMTransport(
        word2vec_service=FakeWord2Vec(),
        require_word2vec=False,
        generation_service=generator,
    )
    provider._prototype_context = lambda query, top_k=3: (
        "Prompt: prior\nResponse: context",
        {
            "available": True,
            "prototype_dataset_reused": True,
            "candidate_count": 1,
            "candidate_only": True,
        },
    )

    response = asyncio.run(
        provider.chat_completion(
            messages=[
                {"role": "system", "content": "HHS_ASSISTANT_MODE=GENERAL_CHAT."},
                {"role": "user", "content": "Tell me about language."},
            ],
            tools=[],
        )
    )

    assert response["choices"][0]["message"]["content"] == "Generated by the native causal model."
    trace = response["hhs_native_trace"]
    assert trace["generation_path"] == "NATIVE_CAUSAL_LM_RAG"
    assert trace["assistant_mode"] == "GENERAL_CHAT"
    assert trace["prototype_retrieval"]["candidate_count"] == 1
    assert trace["runtime_mutation_admitted"] is False
    assert generator.calls[0]["retrieval_context"]


def test_both_mode_explicit_development_intent_routes_tools_before_causal_generation():
    generator = FakeGenerationService()
    provider = HHSNativeLiteRTLMTransport(
        word2vec_service=FakeWord2Vec(),
        require_word2vec=False,
        generation_service=generator,
    )

    response = asyncio.run(
        provider.chat_completion(
            messages=[
                {"role": "system", "content": "HHS_ASSISTANT_MODE=BOTH."},
                {"role": "user", "content": "Inspect the repository and fix the build test."},
            ],
            tools=DEFAULT_HHS_ASSISTANT_TOOLS,
        )
    )

    choice = response["choices"][0]
    assert choice["finish_reason"] == "tool_calls"
    assert any(
        item["function"]["name"] == "hhs_repository_search"
        for item in choice["message"]["tool_calls"]
    )
    assert generator.calls == []


def test_pass219_prototype_compilation_is_cached(monkeypatch):
    import hhs_runtime.hhs_pass219_ethical_text_training_v1 as training

    calls = {"from_repository": 0, "compile": 0, "select": 0}

    class FakeCycle:
        @classmethod
        def from_repository(cls, *args, **kwargs):
            calls["from_repository"] += 1
            return cls()

        def compile_dataset(self, examples, require_word2vec=True):
            calls["compile"] += 1
            return {
                "dataset_hash72": "d" * 72,
                "final_hash216_root": "f" * 64,
                "records": [{
                    "example_id": "prototype-1",
                    "prompt": "What is language?",
                }],
            }

        def select_response_candidate(self, query, dataset, top_k=3):
            calls["select"] += 1
            return {
                "candidate_set_hash72": "c" * 72,
                "results": [{
                    "example_id": "prototype-1",
                    "score": {"numerator": 1, "denominator": 2},
                    "response": "Language carries structured meaning.",
                    "record_hash72": "r" * 72,
                    "hash216_root": "h" * 64,
                    "declared_invariants": ["TRUTH_PRESERVATION"],
                }],
            }

    monkeypatch.setattr(training, "EthicalTextTrainingCycle", FakeCycle)
    monkeypatch.setattr(training, "load_prompt_response_jsonl", lambda path: [object()])

    provider = HHSNativeLiteRTLMTransport(
        word2vec_service=FakeWord2Vec(),
        require_word2vec=False,
        generation_service=FakeGenerationService(),
    )

    first_context, first_meta = provider._prototype_context("language")
    second_context, second_meta = provider._prototype_context("meaning")

    assert first_context
    assert second_context
    assert calls["from_repository"] == 1
    assert calls["compile"] == 1
    assert calls["select"] == 2
    assert first_meta["prototype_dataset_reused"] is False
    assert second_meta["prototype_dataset_reused"] is True
