#include "hhs_p165_mmvs.h"
#include <string.h>
static uint32_t index_of(uint32_t position, uint32_t lane){return position*HHS_P165_LANES+lane;}
hhs_p165_status hhs_p165_frame_clear(hhs_p165_frame *frame){if(!frame)return HHS_P165_INVALID_ARGUMENT;memset(frame->bytes,0,sizeof(frame->bytes));return HHS_P165_OK;}
hhs_p165_status hhs_p165_frame_set(hhs_p165_frame *frame,uint32_t position,uint32_t lane,uint8_t value){uint32_t i,b,bit;if(!frame||value>1u)return HHS_P165_INVALID_ARGUMENT;if(position>=HHS_P165_POSITIONS||lane>=HHS_P165_LANES)return HHS_P165_OUT_OF_RANGE;i=index_of(position,lane);b=i/8u;bit=7u-(i%8u);if(value)frame->bytes[b]|=(uint8_t)(1u<<bit);else frame->bytes[b]&=(uint8_t)~(1u<<bit);return HHS_P165_OK;}
hhs_p165_status hhs_p165_frame_get(const hhs_p165_frame *frame,uint32_t position,uint32_t lane,uint8_t *value){uint32_t i,b,bit;if(!frame||!value)return HHS_P165_INVALID_ARGUMENT;if(position>=HHS_P165_POSITIONS||lane>=HHS_P165_LANES)return HHS_P165_OUT_OF_RANGE;i=index_of(position,lane);b=i/8u;bit=7u-(i%8u);*value=(uint8_t)((frame->bytes[b]>>bit)&1u);return HHS_P165_OK;}
uint32_t hhs_p165_frame_popcount(const hhs_p165_frame *frame){uint32_t total=0u;size_t i;if(!frame)return 0u;for(i=0;i<HHS_P165_FRAME_BYTES;i++){uint8_t v=frame->bytes[i];while(v){total+=(uint32_t)(v&1u);v>>=1u;}}return total;}
hhs_p165_status hhs_p165_frame_residual(const hhs_p165_frame *actual,const hhs_p165_frame *predicted,hhs_p165_frame *residual){size_t i;if(!actual||!predicted||!residual)return HHS_P165_INVALID_ARGUMENT;for(i=0;i<HHS_P165_FRAME_BYTES;i++)residual->bytes[i]=(uint8_t)(actual->bytes[i]^predicted->bytes[i]);return HHS_P165_OK;}
hhs_p165_status hhs_p165_validate_source(const hhs_p165_source_descriptor *source){if(!source)return HHS_P165_INVALID_ARGUMENT;if(source->abi_version!=HHS_P165_ABI_VERSION)return HHS_P165_INVALID_ARGUMENT;if(source->byte_length==0u||source->byte_length>HHS_P165_MAX_SOURCE_BYTES)return HHS_P165_SIZE_BOUND;if(source->authorization_scope==0u)return HHS_P165_INVALID_ARGUMENT;return HHS_P165_OK;}
hhs_p165_status hhs_p165_validate_weight(hhs_p165_rational weight,hhs_p165_rational minimum,hhs_p165_rational maximum){int64_t lower,upper;if(weight.denominator==0u||weight.denominator>UINT32_MAX||minimum.denominator!=1u||maximum.denominator!=1u)return HHS_P165_NONCANONICAL_WEIGHT;if(minimum.numerator < -1000000 || minimum.numerator > 1000000 || maximum.numerator < -1000000 || maximum.numerator > 1000000)return HHS_P165_NONCANONICAL_WEIGHT;lower=minimum.numerator*(int64_t)weight.denominator;upper=maximum.numerator*(int64_t)weight.denominator;if(weight.numerator<lower||weight.numerator>upper)return HHS_P165_OUT_OF_RANGE;return HHS_P165_OK;}
