import './gui-reliability.mjs';
import { $, $$, state, activeFile, persist, setText, log, bytesToBase64, ensureProject } from './visual-ide-state.mjs';
import { showIde, showOther, renderFiles, activateFile, updateLineNumbers, saveFile, createFile, addBrowserFiles, renderSnapshot, renderHash216, openBottomTab, bind3d } from './visual-ide-ui.mjs';
import { ingest, loadSnapshot, interpret, compile, run, runLifecycle, replay, exportEgress } from './visual-ide-runtime.mjs';
import { initProjectLifecycle } from './project-lifecycle.mjs';
import { initIntegratedWorkbench } from './integrated-workbench.mjs';
import { initIntegratedAssistant } from './integrated-assistant.mjs';
import { initIntuitiveIDE } from './intuitive-ide.mjs';

$('#ide-home').onclick = showIde;
$('#assistant-home').addEventListener('click', () => showOther('assistant'), true);
$('#object-workspace').addEventListener('click', () => showOther('workspace'), true);
$('#return-assistant').addEventListener('click', (event) => { event.stopImmediatePropagation(); showIde(); }, true);
$('#open-api').addEventListener('click', (event) => { event.stopImmediatePropagation(); showOther('api'); }, true);
$('#assistant-open-api').addEventListener('click', () => showOther('api'), true);
$$('[data-close-view]').forEach((button) => button.addEventListener('click', (event) => { event.stopImmediatePropagation(); showIde(); }, true));
$('#ide-new-file').onclick = createFile;
$('#ide-save').onclick = saveFile;
$('#ide-upload-trigger').onclick = () => $('#ide-file-input').click();
$('#ide-file-input').onchange = async (event) => { if (event.target.files?.length) await addBrowserFiles([...event.target.files], ingest); event.target.value = ''; };
$('#ide-ingest').onclick = ingest; $('#ide-interpret').onclick = interpret; $('#ide-compile').onclick = compile; $('#ide-run').onclick = run; $('#ide-run-lifecycle').onclick = runLifecycle; $('#ide-replay').onclick = replay; $('#ide-egress').onclick = exportEgress; $('#ide-download-egress').onclick = exportEgress;
const commands = { new: createFile, save: saveFile, ingress: ingest, interpret, compile, run, lifecycle: runLifecycle, egress: exportEgress };
$$('[data-ide-command]').forEach((button) => { button.onclick = () => commands[button.dataset.ideCommand]?.(); });
$$('.ide-bottom-tabs button').forEach((button) => { button.onclick = () => openBottomTab(button.dataset.bottomTab); });
$$('[data-stage]').forEach((button) => { button.onclick = () => ({ ingress, index: loadSnapshot, snapshot: loadSnapshot, interpret, compile, execute: run, egress: exportEgress }[button.dataset.stage]?.()); });
const editor = $('#ide-source-editor');
editor.oninput = () => { const file = activeFile(); if (!file.bytesB64) { file.content = editor.value; file.dirty = true; persist(); renderFiles(); } updateLineNumbers(); };
['click', 'keyup', 'select'].forEach((eventName) => editor.addEventListener(eventName, updateLineNumbers));
const zone = $('#ide-drop-zone');
['dragenter', 'dragover'].forEach((eventName) => zone.addEventListener(eventName, (event) => { event.preventDefault(); zone.classList.add('drag-active'); }));
['dragleave', 'drop'].forEach((eventName) => zone.addEventListener(eventName, (event) => { event.preventDefault(); zone.classList.remove('drag-active'); }));
zone.ondrop = async (event) => { if (event.dataTransfer?.files?.length) await addBrowserFiles([...event.dataTransfer.files], ingest); };
const layout = $('#ide-layout'); layout.dataset.mobilePane = 'editor';
$$('.ide-mobile-dock button').forEach((button) => { button.onclick = () => { $$('.ide-mobile-dock button').forEach((item) => item.classList.toggle('active', item === button)); if (button.dataset.mobilePane === 'explorer') $('#registry-nav').classList.add('open'); else layout.dataset.mobilePane = button.dataset.mobilePane; }; });
document.addEventListener('keydown', (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 's') { event.preventDefault(); saveFile(); } if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') { event.preventDefault(); runLifecycle(); } });
window.HHSVisualIDE = Object.freeze({ state, show: showIde, ingest, snapshot: loadSnapshot, interpret, compile, run, lifecycle: runLifecycle, replay, egress: exportEgress });
renderFiles(); activateFile(state.activePath); renderSnapshot({ projection_b64: bytesToBase64(new Uint8Array(648)), projection_hash72: 'GENESIS' }); renderHash216({ ingestion_operation_hash216: 'GENESIS', ingestion_positions_hash216: [] }); bind3d(); showIde(); initProjectLifecycle(); initIntegratedWorkbench(); initIntegratedAssistant(); initIntuitiveIDE(); setText('#ide-registry-state', 'LIVE');
void ensureProject().then((projectId) => log(`Workspace authority bound to ${projectId}.`)).catch((error) => log(`Workspace initialization deferred: ${error.message}`));
