"""
HHS Goal State / Attractor Engine v1
====================================

Directed state-selection layer over the HHS execution stack.

The attractor engine defines target constraints over HHS states and transition
receipts, evaluates candidate states generated by the PhaseTransportVM, selects
valid convergence edges, and records attractor attempts into the Memory Ledger.

Pipeline:

    goal specification
    -> token candidate generation
    -> Lo Shu phase embedding
    -> HHS attention
    -> PhaseTransportVM kernel-gated transitions
    -> attractor scoring
    -> ledger append + replay validation

No candidate is accepted unless it is already kernel-valid and committed by the
PhaseTransportVM.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from enum import Enum
from fractions import Fraction
from pathlib import Path
from typing import Dict, Iterable, List, Sequence

from hhs_runtime.hhs_attention_operator_v1 import AttentionReceipt, attention_pass
from hhs_runtime.hhs_loshu_phase_embedding_v1 import (
    LO_SHU_CELLS,
    TORUS_ORDER,
    EmbeddingReceipt,
    PhaseEmbeddingState,
    embed_sequence,
    hash72_digest,
)
from hhs_runtime.hhs_memory_ledger_replay_v1 import MemoryLedger, replay_ledger
from hhs_runtime.hhs_phase_transport_vm_v1 import (
    TransitionStatus,
    VMRunReceipt,
    run_attention_transitions,
)


class AttractorStatus(str, Enum):
    CONVERGED = "CONVERGED"
    ADVANCED = "ADVANCED"
    STALLED = "STALLED"
    QUARANTINED = "QUARANTINED"


@dataclass(frozen=True)
class GoalState:
    """Target constraints for directed HHS convergence."""

    name: str
    target_token: str | None = None
    target_phase_index: int | None = None
    target_lo_shu_cell: int | None = None
    target_dna_prefix: str | None = None
    target_hash72_prefix: str | None = None
    require_committed_transition: bool = True

    def to_dict(self) -> Dict[str, object]:
        return asdict(self)


@dataclass(frozen=True)
class AttractorScore:
    """Exact goal-proximity score for one embedded state."""

    state_hash72: str
    token: str
    position: int
    dimension: int
    phase_component: Fraction
    loshu_component: Fraction
    dna_component: Fraction
    hash72_component: Fraction
    token_component: Fraction
    invariant_component: Fraction
    total_score: Fraction
    receipt_hash72: str

    def to_dict(self) -> Dict[str, object]:
        data = asdict(self)
        for key, value in list(data.items()):
            if isinstance(value, Fraction):
                data[key] = f"{value.numerator}/{value.denominator}"
        return data


@dataclass(frozen=True)
class AttractorStepReceipt:
    """One directed attractor step."""

    goal: GoalState
    attention_receipt_hash72: str
    vm_receipt_hash72: str
    selected_state_hash72: str | None
    selected_transition_receipt_hash72: str | None
    selected_score: AttractorScore | None
    status: AttractorStatus
    receipt_hash72: str

    def to_dict(self) -> Dict[str, object]:
        return {
            "goal": self.goal.to_dict(),
            "attention_receipt_hash72": self.attention_receipt_hash72,
            "vm_receipt_hash72": self.vm_receipt_hash72,
            "selected_state_hash72": self.selected_state_hash72,
            "selected_transition_receipt_hash72": self.selected_transition_receipt_hash72,
            "selected_score": self.selected_score.to_dict() if self.selected_score else None,
            "status": self.status.value,
            "receipt_hash72": self.receipt_hash72,
        }


@dataclass(frozen=True)
class AttractorRunReceipt:
    """Full attractor run receipt."""

    module: str
    goal: GoalState
    steps: List[AttractorStepReceipt]
    ledger_commit_receipt: Dict[str, object]
    replay_receipt: Dict[str, object]
    status: AttractorStatus
    receipt_hash72: str

    def to_dict(self) -> Dict[str, object]:
        return {
            "module": self.module,
            "goal": self.goal.to_dict(),
            "steps": [step.to_dict() for step in self.steps],
            "ledger_commit_receipt": self.ledger_commit_receipt,
            "replay_receipt": self.replay_receipt,
            "status": self.status.value,
            "receipt_hash72": self.receipt_hash72,
        }


def _fraction_prefix_score(value: str, prefix: str | None) -> Fraction:
    if not prefix:
        return Fraction(1, 1)
    if not value:
        return Fraction(0, 1)
    limit = min(len(value), len(prefix))
    matches = sum(1 for a, b in zip(value[:limit], prefix[:limit]) if a == b)
    return Fraction(matches, len(prefix))


def _phase_goal_score(state: PhaseEmbeddingState, target: int | None) -> Fraction:
    if target is None:
        return Fraction(1, 1)
    target %= TORUS_ORDER
    delta = abs(state.phase_index - target) % TORUS_ORDER
    distance = min(delta, TORUS_ORDER - delta)
    return Fraction(TORUS_ORDER // 2 - distance, TORUS_ORDER // 2)


def _loshu_goal_score(state: PhaseEmbeddingState, target: int | None) -> Fraction:
    if target is None:
        return Fraction(1, 1)
    target %= LO_SHU_CELLS
    sr, sc = divmod(state.lo_shu.cell_index, 9)
    tr, tc = divmod(target, 9)
    distance = max(abs(sr - tr), abs(sc - tc))
    return Fraction(8 - distance, 8)


def score_state_against_goal(state: PhaseEmbeddingState, goal: GoalState) -> AttractorScore:
    """Score a single HHS state against a goal using exact rational components."""

    phase = _phase_goal_score(state, goal.target_phase_index)
    loshu = _loshu_goal_score(state, goal.target_lo_shu_cell)
    dna = _fraction_prefix_score(state.xyzw_dna, goal.target_dna_prefix)
    h72 = _fraction_prefix_score(state.hash72, goal.target_hash72_prefix)
    token = Fraction(1, 1) if goal.target_token is None or state.token == goal.target_token else Fraction(0, 1)
    invariant = Fraction(1, 1) if all(state.invariants.values()) else Fraction(0, 1)
    total = (phase + loshu + dna + h72 + token + invariant) / 6
    receipt = hash72_digest(("attractor_score_v1", goal.to_dict(), state.receipt_hash72, phase, loshu, dna, h72, token, invariant, total))
    return AttractorScore(
        state_hash72=state.hash72,
        token=state.token,
        position=state.position,
        dimension=state.dimension,
        phase_component=phase,
        loshu_component=loshu,
        dna_component=dna,
        hash72_component=h72,
        token_component=token,
        invariant_component=invariant,
        total_score=total,
        receipt_hash72=receipt,
    )


def _converged(score: AttractorScore) -> bool:
    return score.total_score == Fraction(1, 1)


def _state_by_hash(embedding: EmbeddingReceipt) -> Dict[str, PhaseEmbeddingState]:
    return {state.hash72: state for state in embedding.states}


def _select_transition_for_goal(
    embedding: EmbeddingReceipt,
    attention: AttentionReceipt,
    vm_receipt: VMRunReceipt,
    goal: GoalState,
) -> tuple[PhaseEmbeddingState | None, str | None, AttractorScore | None, AttractorStatus]:
    """Select the highest-scoring committed target state reachable this step."""

    lookup = _state_by_hash(embedding)
    transition_by_hash = {receipt.receipt_hash72: receipt for receipt in vm_receipt.transition_receipts}

    candidates: List[tuple[AttractorScore, PhaseEmbeddingState, str]] = []
    for transition_receipt in vm_receipt.transition_receipts:
        if goal.require_committed_transition and transition_receipt.status != TransitionStatus.COMMITTED:
            continue
        target_hash = transition_receipt.transition.target_hash72
        state = lookup.get(target_hash)
        if state is None:
            continue
        score = score_state_against_goal(state, goal)
        candidates.append((score, state, transition_receipt.receipt_hash72))

    if not candidates:
        return None, None, None, AttractorStatus.QUARANTINED

    candidates.sort(key=lambda item: (item[0].total_score, item[0].receipt_hash72), reverse=True)
    score, state, transition_receipt_hash = candidates[0]
    status = AttractorStatus.CONVERGED if _converged(score) else AttractorStatus.ADVANCED
    return state, transition_receipt_hash, score, status


def attractor_step(tokens: Sequence[str], goal: GoalState, d_model: int = 72, dimensions: int = 4, top_k: int = 2) -> AttractorStepReceipt:
    """Run one goal-directed step through embedding, attention, VM gates, and scoring."""

    embedding = embed_sequence(tokens, d_model=d_model, dimensions=dimensions)
    attention = attention_pass(embedding, top_k=top_k)
    vm_receipt = run_attention_transitions(embedding, attention)
    selected_state, selected_transition_hash, selected_score, status = _select_transition_for_goal(embedding, attention, vm_receipt, goal)
    if selected_state is None and status != AttractorStatus.QUARANTINED:
        status = AttractorStatus.STALLED

    receipt = hash72_digest(
        (
            "attractor_step_v1",
            goal.to_dict(),
            attention.receipt_hash72,
            vm_receipt.receipt_hash72,
            selected_state.hash72 if selected_state else None,
            selected_transition_hash,
            selected_score.receipt_hash72 if selected_score else None,
            status.value,
        )
    )
    return AttractorStepReceipt(
        goal=goal,
        attention_receipt_hash72=attention.receipt_hash72,
        vm_receipt_hash72=vm_receipt.receipt_hash72,
        selected_state_hash72=selected_state.hash72 if selected_state else None,
        selected_transition_receipt_hash72=selected_transition_hash,
        selected_score=selected_score,
        status=status,
        receipt_hash72=receipt,
    )


def run_attractor(
    tokens: Sequence[str],
    goal: GoalState,
    d_model: int = 72,
    dimensions: int = 4,
    top_k: int = 2,
    max_steps: int = 3,
    ledger_path: str | Path = "demo_reports/hhs_attractor_ledger_v1.json",
) -> AttractorRunReceipt:
    """
    Run repeated goal-directed attractor steps and record them in the ledger.

    The token set is stable in v1; later engines can mutate candidate tokens via
    kernel-approved rewrite operators.  This version establishes the directed
    scoring, gating, commit, and replay path.
    """

    if max_steps <= 0:
        raise ValueError("max_steps must be positive")

    steps: List[AttractorStepReceipt] = []
    final_status = AttractorStatus.STALLED
    for _ in range(max_steps):
        step = attractor_step(tokens, goal, d_model=d_model, dimensions=dimensions, top_k=top_k)
        steps.append(step)
        final_status = step.status
        if step.status in (AttractorStatus.CONVERGED, AttractorStatus.QUARANTINED):
            break

    ledger = MemoryLedger(ledger_path)
    payloads = [step.to_dict() for step in steps]
    commit_receipt = ledger.append_payloads("attractor_step_receipt_v1", payloads)
    replay_receipt = replay_ledger(ledger_path)
    run_hash = hash72_digest(
        (
            "attractor_run_v1",
            goal.to_dict(),
            [step.receipt_hash72 for step in steps],
            commit_receipt.receipt_hash72,
            replay_receipt.receipt_hash72,
            final_status.value,
        )
    )
    return AttractorRunReceipt(
        module="hhs_goal_attractor_engine_v1",
        goal=goal,
        steps=steps,
        ledger_commit_receipt=commit_receipt.to_dict(),
        replay_receipt=replay_receipt.to_dict(),
        status=final_status,
        receipt_hash72=run_hash,
    )


def demo() -> Dict[str, object]:
    path = Path("demo_reports/hhs_attractor_ledger_demo_v1.json")
    if path.exists():
        path.unlink()
    goal = GoalState(
        name="LoShu-Hash72 convergence demo",
        target_token="Hash72",
        target_phase_index=36,
        target_lo_shu_cell=40,
        target_dna_prefix="x",
    )
    receipt = run_attractor(
        ["HHS", "Hash72", "LoShu", "xyzw"],
        goal=goal,
        d_model=72,
        dimensions=4,
        top_k=2,
        max_steps=2,
        ledger_path=path,
    )
    return receipt.to_dict()


if __name__ == "__main__":
    import json

    print(json.dumps(demo(), indent=2, sort_keys=True, ensure_ascii=False))
