"""
HHS Audio Phase Transport Decoder v1
====================================

Decodes deterministic HHS audio phase manifests/stems back into symbolic phase
observations for round-trip validation.

The decoder is intentionally conservative:
- reads WAV stems generated by hhs_audio_phase_transport_encoder_v1
- estimates dominant zero-crossing frequency per item window
- maps estimated frequency back to nearest 72-phase bin
- compares decoded bins against the manifest phase_index values

This is not speech recognition. It is audio transport verification.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any, Dict, List
import json
import math
import wave

from hhs_runtime.hhs_loshu_phase_embedding_v1 import hash72_digest

RING = 72
BASE_FREQ = Fraction(220, 1)


@dataclass(frozen=True)
class AudioDecodedItem:
    item_id: str
    text: str
    expected_phase_index: int
    decoded_phase_index: int
    phase_error: int
    estimated_frequency_hz: str
    status: str
    decoded_hash72: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class AudioRoundTripReceipt:
    manifest_hash72: str
    decoded_items: List[AudioDecodedItem]
    exact_matches: int
    total_items: int
    max_phase_error: int
    status: str
    receipt_hash72: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "manifest_hash72": self.manifest_hash72,
            "decoded_items": [d.to_dict() for d in self.decoded_items],
            "exact_matches": self.exact_matches,
            "total_items": self.total_items,
            "max_phase_error": self.max_phase_error,
            "status": self.status,
            "receipt_hash72": self.receipt_hash72,
        }


def _read_wav_samples(path: Path) -> tuple[int, List[float]]:
    with wave.open(str(path), "rb") as wf:
        sample_rate = wf.getframerate()
        width = wf.getsampwidth()
        frames = wf.readframes(wf.getnframes())
    if width != 2:
        raise ValueError(f"expected 16-bit PCM WAV, got sample width {width}")
    samples: List[float] = []
    for i in range(0, len(frames), 2):
        samples.append(int.from_bytes(frames[i:i+2], "little", signed=True) / 32767.0)
    return sample_rate, samples


def _estimate_frequency(samples: List[float], sample_rate: int) -> float:
    if len(samples) < 4:
        return 0.0
    crossings = 0
    prev = samples[0]
    for cur in samples[1:]:
        if (prev <= 0 < cur) or (prev >= 0 > cur):
            crossings += 1
        prev = cur
    seconds = len(samples) / sample_rate
    if seconds <= 0:
        return 0.0
    return crossings / (2.0 * seconds)


def frequency_to_phase(freq: float) -> int:
    if freq <= 0:
        return 0
    p = round(RING * math.log(freq / float(BASE_FREQ), 2))
    return p % RING


def _phase_error(a: int, b: int) -> int:
    d = abs((a % RING) - (b % RING))
    return min(d, RING - d)


def decode_audio_phase_manifest(manifest_path: str | Path) -> AudioRoundTripReceipt:
    path = Path(manifest_path)
    manifest = json.loads(path.read_text(encoding="utf-8"))
    sample_rate = int(manifest.get("sample_rate", 48_000))
    stems = manifest.get("stems", {})
    items = manifest.get("items", [])

    stem_cache: Dict[str, tuple[int, List[float]]] = {}
    decoded: List[AudioDecodedItem] = []

    for item in items:
        symbol = str(item.get("symbol", "x"))
        if symbol in {"x", "xy"}:
            stem = "x"
        elif symbol in {"y", "yx"}:
            stem = "y"
        elif symbol in {"z", "zw"}:
            stem = "z"
        elif symbol in {"w", "wz"}:
            stem = "w"
        else:
            stem = "closure"
        stem_path = Path(stems.get(stem, ""))
        if stem not in stem_cache:
            stem_cache[stem] = _read_wav_samples(stem_path)
        sr, all_samples = stem_cache[stem]
        start = int(item.get("start_sample", 0))
        dur = int(item.get("duration_samples", 1))
        window = all_samples[start:start + dur]
        est = _estimate_frequency(window, sr or sample_rate)
        decoded_phase = frequency_to_phase(est)
        expected = int(item.get("phase_index", 0)) % RING
        err = _phase_error(expected, decoded_phase)
        status = "MATCH" if err <= 1 else "DRIFT"
        h = hash72_digest(("hhs_audio_decoded_item_v1", item.get("item_hash72"), expected, decoded_phase, err, str(est), status), width=24)
        decoded.append(AudioDecodedItem(str(item.get("id", "")), str(item.get("text", "")), expected, decoded_phase, err, str(Fraction.from_float(est).limit_denominator(1_000_000)), status, h))

    exact = sum(1 for d in decoded if d.status == "MATCH")
    max_err = max([d.phase_error for d in decoded] or [0])
    status = "ROUND_TRIP_LOCKED" if decoded and exact == len(decoded) else "ROUND_TRIP_DRIFT"
    receipt_hash = hash72_digest(("hhs_audio_round_trip_receipt_v1", manifest.get("manifest_hash72"), [d.to_dict() for d in decoded], exact, max_err, status), width=24)
    return AudioRoundTripReceipt(str(manifest.get("manifest_hash72", "")), decoded, exact, len(decoded), max_err, status, receipt_hash)


def main() -> None:
    receipt = decode_audio_phase_manifest("demo_reports/audio_phase_transport/hhs_audio_phase_manifest.json")
    print(json.dumps(receipt.to_dict(), indent=2, sort_keys=True, ensure_ascii=False))


if __name__ == "__main__":
    main()
