@@
   const autocorrectionSuggestions = result?.autocorrections?.suggestions ?? [];
   const branchFrontier = result?.correctionBranchFrontier;
   const symbolicCandidates = result?.symbolic_substitution?.candidates ?? [];
+  const ghostCandidate = symbolicCandidates[0];
@@
       <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginTop: 10, fontSize: 11 }}>
         <div style={{ background: '#03110b', border: '1px solid #064', borderRadius: 6, padding: 8 }}><div style={{ color: '#8cffb0' }}>Interpreter</div><div>source {short(result?.interpreter?.receipt?.source_hash72)}</div><div>stress {short(result?.interpreter?.receipt?.stress_hash72)}</div><div>ir {short(result?.interpreter?.receipt?.ir_hash72)}</div></div>
         <div style={{ background: solverStatus === 'QUARANTINED' ? '#1c0508' : '#03110b', border: `1px solid ${solverStatus === 'QUARANTINED' ? '#f04' : '#064'}`, borderRadius: 6, padding: 8 }}><div style={{ color: solverStatus === 'QUARANTINED' ? '#ff8a8a' : '#8cffb0' }}>Solver</div><div>status {solverStatus}</div><div>diagnostics {calcDoc.diagnostics.length}</div><div>items {calcDoc.doc.nodes.length}</div></div>
       </div>
+      {ghostCandidate ? <div style={{ marginTop: 8, background: '#090214', border: '1px solid #65f', borderRadius: 6, padding: 8, fontSize: 11 }}><div style={{ color: '#caa8ff', fontWeight: 700 }}>Ghost Preview · Top Symbolic Path</div><div style={{ color: '#ddd', opacity: 0.78 }}>{ghostCandidate.candidate_text}</div><div style={{ color: '#9ad' }}>score {ghostCandidate.score} · phases [{ghostCandidate.projected_phases?.join(' → ')}]</div><button onClick={() => applyCandidate(ghostCandidate.candidate_text)} style={{ marginTop: 4, background: '#7a5cff', color: '#fff', border: 0, borderRadius: 4, padding: '3px 8px', fontWeight: 700 }}>APPLY GHOST</button></div> : null}
       {symbolicCandidates.length ? <div style={{ marginTop: 8, background: '#021008', border: '1px solid #0a7', borderRadius: 6, padding: 8, fontSize: 11 }}><div style={{ color: '#8cffb0', fontWeight: 700 }}>Symbolic Substitution Paths</div>{symbolicCandidates.slice(0, 6).map((c: any) => <div key={c.candidate_hash72} style={{ marginTop: 6, borderTop: '1px solid rgba(255,255,255,0.12)', paddingTop: 6 }}><div style={{ color: '#cfffff' }}>{c.candidate_text}</div><div style={{ color: '#9ad' }}>score {c.score} · phases [{c.projected_phases?.join(' → ')}] · {c.reason}</div><button onClick={() => applyCandidate(c.candidate_text)} style={{ marginTop: 4, background: '#00aa77', color: '#001', border: 0, borderRadius: 4, padding: '3px 8px', fontWeight: 700 }}>APPLY</button></div>)}</div> : null}
