"""Pass 213 Iteration 9 hardened governed surface.

This wrapper separates each canonical source receipt from the public projection
receipt. The append-only projection chain always authenticates its own domain;
source receipts remain visible only as committed public data.
"""
from __future__ import annotations

import os
from pathlib import Path
import threading
from typing import Any, Mapping

from hhs_backend.runtime import hhs_pass213_governed_surface_v1 as _v1

# Re-export the stable Iteration 9 contract and error vocabulary.
CONTRACT = _v1.CONTRACT
ITERATION = _v1.ITERATION
RUNTIME_CLASSIFICATION = _v1.RUNTIME_CLASSIFICATION
CAPABILITY_SCHEMA = _v1.CAPABILITY_SCHEMA
RESPONSE_SCHEMA = _v1.RESPONSE_SCHEMA
PROJECTION_SCHEMA = _v1.PROJECTION_SCHEMA
FULL_HYDRATION_DOMAIN = _v1.FULL_HYDRATION_DOMAIN
VM5184_G243_DOMAIN = _v1.VM5184_G243_DOMAIN
ZERO_HASH216 = _v1.ZERO_HASH216

KIND_COMPILED_ROM = _v1.KIND_COMPILED_ROM
KIND_INVENTORY = _v1.KIND_INVENTORY
KIND_MOVING_TENSOR = _v1.KIND_MOVING_TENSOR
KIND_TIMESTAMP_ANCHOR = _v1.KIND_TIMESTAMP_ANCHOR
KIND_RECEIPT = _v1.KIND_RECEIPT
KINDS = _v1.KINDS

SCOPE_COMPILED_READ = _v1.SCOPE_COMPILED_READ
SCOPE_INVENTORY_VERIFY = _v1.SCOPE_INVENTORY_VERIFY
SCOPE_TENSOR_READ = _v1.SCOPE_TENSOR_READ
SCOPE_TENSOR_VERIFY = _v1.SCOPE_TENSOR_VERIFY
SCOPE_TIMESTAMP_READ = _v1.SCOPE_TIMESTAMP_READ
SCOPE_INTEGRITY_VERIFY = _v1.SCOPE_INTEGRITY_VERIFY
SCOPE_RECEIPT_READ = _v1.SCOPE_RECEIPT_READ
ALLOWED_SCOPES = _v1.ALLOWED_SCOPES

Pass213SurfaceError = _v1.Pass213SurfaceError
Pass213SurfaceAuthorizationError = _v1.Pass213SurfaceAuthorizationError
Pass213SurfaceValidationError = _v1.Pass213SurfaceValidationError
Pass213SurfaceNotFoundError = _v1.Pass213SurfaceNotFoundError
Pass213SurfaceIntegrityError = _v1.Pass213SurfaceIntegrityError
CapabilityClaims = _v1.CapabilityClaims
CapabilityAuthority = _v1.CapabilityAuthority
PublicProjectionRecord = _v1.PublicProjectionRecord
assert_public_projection_safe = _v1.assert_public_projection_safe
sanitize_public_projection = _v1.sanitize_public_projection


class GovernedProjectionStore(_v1.GovernedProjectionStore):
    """Projection store that never substitutes a source receipt for its own."""

    def publish(
        self,
        *,
        kind: str,
        object_id: str,
        source_root_hash216: str,
        public_data: Mapping[str, Any],
        receipt_hash72: str | None = None,
        published_timestamp_ns: int | None = None,
    ) -> PublicProjectionRecord:
        # `receipt_hash72` belongs to the source authority and may use a different
        # domain. It must be carried inside public_data, never as the projection
        # chain's receipt. The projection receipt is generated by the parent.
        return super().publish(
            kind=kind,
            object_id=object_id,
            source_root_hash216=source_root_hash216,
            public_data=public_data,
            receipt_hash72=None,
            published_timestamp_ns=published_timestamp_ns,
        )


class Pass213GovernedSurface(_v1.Pass213GovernedSurface):
    """Hardened type marker for the API and CLI transports."""


_DEFAULT_LOCK = threading.RLock()
_DEFAULT_SURFACE: Pass213GovernedSurface | None = None


def get_default_pass213_surface() -> Pass213GovernedSurface:
    global _DEFAULT_SURFACE
    with _DEFAULT_LOCK:
        if _DEFAULT_SURFACE is None:
            root = Path(os.environ.get(
                "HHS_PASS213_SURFACE_STATE_DIR",
                str(Path.home() / ".local" / "state" / "hhs" / "pass213" / "surface"),
            )).expanduser().resolve()
            store_key = _v1._load_or_create_key(
                root / "projection.key", "HHS_PASS213_SURFACE_KEY_HEX"
            )
            capability_key = _v1._load_or_create_key(
                root / "capability.key", "HHS_PASS213_CAPABILITY_KEY_HEX"
            )
            _DEFAULT_SURFACE = Pass213GovernedSurface(
                projection_store=GovernedProjectionStore(
                    database_path=root / "public-projections.sqlite3",
                    root_key=store_key,
                ),
                capability_authority=CapabilityAuthority(
                    root_key=capability_key,
                    epoch=int(os.environ.get("HHS_PASS213_CAPABILITY_EPOCH", "1")),
                ),
            )
        return _DEFAULT_SURFACE


def configure_default_pass213_surface(
    surface: Pass213GovernedSurface | None,
) -> Pass213GovernedSurface | None:
    global _DEFAULT_SURFACE
    with _DEFAULT_LOCK:
        previous = _DEFAULT_SURFACE
        _DEFAULT_SURFACE = surface
        return previous
