"""Pass 058 service surface: hhs_canonical_federated_merge_decision_v1."""
from hhs_backend.runtime.hhs_canonical_federated_state_reconciliation_v1 import validate_canonical_merge

def canonical_federated_merge_decision_v1_self_test():
    from hhs_backend.runtime.hhs_canonical_federated_state_reconciliation_v1 import canonical_federated_state_reconciliation_self_test
    return canonical_federated_state_reconciliation_self_test()
