#ifndef HHS_PASS219_GENERATION_INTEGRITY_V1_H
#define HHS_PASS219_GENERATION_INTEGRITY_V1_H

#include "hhs_runtime_exact_abi_v1_1_base.h"

#include <stdint.h>

/*
 * Pass 219 generation-integrity proof surface.
 *
 * These declarations are compile-time invariants, not advisory comments.
 * They describe the canonical VM81 mutation boundary. Provider-managed
 * allocations used by the PQC implementation remain non-canonical scratch
 * state and are verified separately by the repository integrity gate.
 */
#define HHS_PASS219_GENERATION_INTEGRITY_VERSION UINT32_C(0x00010000)
#define HHS_PASS219_GENERATION_INTEGRITY_NO_UNCHECKED_CANONICAL_MUTATION UINT32_C(1)
#define HHS_PASS219_GENERATION_INTEGRITY_NO_HOST_ESCALATION UINT32_C(1)
#define HHS_PASS219_GENERATION_INTEGRITY_HALT_ON_DIVERGENCE UINT32_C(1)
#define HHS_PASS219_GENERATION_INTEGRITY_CANONICAL_VM81_DYNAMIC_ALLOCATION UINT32_C(0)
#define HHS_PASS219_GENERATION_INTEGRITY_PROVIDER_SCRATCH_NONCANONICAL UINT32_C(1)
#define HHS_PASS219_GENERATION_INTEGRITY_VM81_BYTES UINT32_C(648)
#define HHS_PASS219_GENERATION_INTEGRITY_VM81_BITS UINT32_C(5184)
#define HHS_PASS219_GENERATION_INTEGRITY_VM81_CELLS UINT32_C(81)
#define HHS_PASS219_GENERATION_INTEGRITY_VM81_WORD_BITS UINT32_C(64)

#if defined(__cplusplus)
#define HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(expr, msg) static_assert((expr), msg)
#else
#define HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(expr, msg) _Static_assert((expr), msg)
#endif

HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_EXACT_VM81_CELLS == HHS_PASS219_GENERATION_INTEGRITY_VM81_CELLS,
    "VM81 cell-count drift");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_EXACT_VM81_WORD_BITS == HHS_PASS219_GENERATION_INTEGRITY_VM81_WORD_BITS,
    "VM81 word-width drift");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_EXACT_VM81_FRAME_BITS == HHS_PASS219_GENERATION_INTEGRITY_VM81_BITS,
    "VM81 bit geometry drift");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_EXACT_VM81_FRAME_BYTES == HHS_PASS219_GENERATION_INTEGRITY_VM81_BYTES,
    "VM81 byte geometry drift");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_EXACT_HASH72_COORDS == HHS_PASS219_GENERATION_INTEGRITY_VM81_BITS,
    "Hash72/VM5184 coordinate drift");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    sizeof(HHSExactVM81Frame) == HHS_PASS219_GENERATION_INTEGRITY_VM81_BYTES,
    "VM81 frame layout drift");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_PASS219_GENERATION_INTEGRITY_NO_UNCHECKED_CANONICAL_MUTATION == UINT32_C(1),
    "unchecked canonical mutation must remain disabled");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_PASS219_GENERATION_INTEGRITY_NO_HOST_ESCALATION == UINT32_C(1),
    "host escalation must remain disabled");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_PASS219_GENERATION_INTEGRITY_HALT_ON_DIVERGENCE == UINT32_C(1),
    "divergence must fail closed");
HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT(
    HHS_PASS219_GENERATION_INTEGRITY_CANONICAL_VM81_DYNAMIC_ALLOCATION == UINT32_C(0),
    "canonical VM81 state must not depend on dynamic allocation");

#undef HHS_PASS219_GENERATION_INTEGRITY_STATIC_ASSERT

#endif
