#ifndef HHS_PASS219_GLOBAL_CANONICAL_DEFAULTS_1_0_H
#define HHS_PASS219_GLOBAL_CANONICAL_DEFAULTS_1_0_H
#include "hhs_runtime_exact_abi_v1_1_base.h"
#include "hhs_pass219_global_latency_policy_25_3_1_0.h"
#include "hhs_pass219_holographic_harmonic_window_25_3_1_0.h"
#ifdef __cplusplus
extern "C" {
#endif
#define HHS_EXACT_PASS219_GLOBAL_DEFAULT_VERSION_MAJOR 1U
#define HHS_EXACT_PASS219_GLOBAL_DEFAULT_VERSION_MINOR 0U
#define HHS_EXACT_PASS219_GLOBAL_DEFAULT_VERSION_PATCH 0U
#define HHS_EXACT_PASS219_GLOBAL_DEFAULT_WIRED_CEILING 218U
#define HHS_EXACT_PASS219_GLOBAL_DEFAULT_WIRED_FLOOR 186U
#define HHS_EXACT_PASS219_GLOBAL_DEFAULT_BINDING_COUNT 35U
#define HHS_EXACT_PASS219_GLOBAL_LATENCY_DEFAULT_REQUIRED 1U
#define HHS_EXACT_PASS219_HOLOGRAPHIC_WINDOW_DEFAULT_REQUIRED 1U
typedef enum HHSExactPass219BindingVariant { HHS_EXACT_PASS219_BINDING_VARIANT_NONE=0, HHS_EXACT_PASS219_BINDING_VARIANT_A=1, HHS_EXACT_PASS219_BINDING_VARIANT_B=2, HHS_EXACT_PASS219_BINDING_VARIANT_C=3 } HHSExactPass219BindingVariant;
typedef struct HHSExactPass219CumulativeBindingKeyV1 { uint16_t pass_number; uint8_t variant; uint8_t reserved; } HHSExactPass219CumulativeBindingKeyV1;
typedef struct HHSExactPass219GlobalCanonicalDefaultPolicyV1 {
 uint32_t struct_size; uint32_t version; uint32_t numbered_passes_are_additive; uint32_t successful_implementations_must_remain_reachable; uint32_t standalone_passes_allowed; uint32_t isolated_native_project_is_canonical_substitute; uint32_t cross_cutting_defaults_are_mandatory; uint32_t retroactive_repair_forward_required; uint32_t grandfather_bypass_allowed; uint32_t explicit_upgrade_or_deprecation_required; uint32_t singleton_vm81_authority_preserved; uint32_t exact_symbolic_authority_required; uint32_t wired_ceiling_pass; uint32_t wired_floor_pass; uint32_t registered_binding_count;
} HHSExactPass219GlobalCanonicalDefaultPolicyV1;
HHS_EXACT_API uint32_t hhs_exact_pass219_global_canonical_defaults_version(void);
HHS_EXACT_API HHSExactStatus hhs_exact_pass219_global_canonical_defaults_policy(HHSExactPass219GlobalCanonicalDefaultPolicyV1 *out_policy);
HHS_EXACT_API HHSExactStatus hhs_exact_pass219_global_canonical_defaults_validate(void);
HHS_EXACT_API HHSExactStatus hhs_exact_pass219_global_canonical_defaults_validate_latency_policy(void);
HHS_EXACT_API HHSExactStatus hhs_exact_pass219_global_canonical_defaults_validate_holographic_window(void);
HHS_EXACT_API size_t hhs_exact_pass219_global_canonical_defaults_binding_count(void);
HHS_EXACT_API HHSExactStatus hhs_exact_pass219_global_canonical_defaults_binding_at(size_t index,HHSExactPass219CumulativeBindingKeyV1 *out_binding);
#ifdef __cplusplus
}
#endif
#endif
