#include "hhs_pass219_language_processing_membrane_1_0.h"
#include <assert.h>
#include <string.h>

static void fill_hash(char out[HHS_EXACT_HASH72_STRLEN], char symbol) {
    size_t i;
    for (i = 0U; i < HHS_EXACT_HASH72_LEN; ++i) out[i] = symbol;
    out[HHS_EXACT_HASH72_LEN] = '\0';
}

static uint32_t relation_for(uint32_t layer) {
    switch (layer) {
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_VERBATIM_SOURCE: return HHS_EXACT_PASS219_LANGUAGE_RELATION_IDENTITY;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_TOKEN_TENSOR: return HHS_EXACT_PASS219_LANGUAGE_RELATION_OCCURRENCE_OF;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_LEXICAL_RELATION: return HHS_EXACT_PASS219_LANGUAGE_RELATION_SYNONYM;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_GRAMMAR_SYNTAX: return HHS_EXACT_PASS219_LANGUAGE_RELATION_GRAMMAR;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_PROPOSITION: return HHS_EXACT_PASS219_LANGUAGE_RELATION_PROPOSITION;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_AMBIGUITY: return HHS_EXACT_PASS219_LANGUAGE_RELATION_AMBIGUITY_ALTERNATIVE;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_TRANSLATION_REGISTER: return HHS_EXACT_PASS219_LANGUAGE_RELATION_TRANSLATION;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_METAPHOR_ANALOGY: return HHS_EXACT_PASS219_LANGUAGE_RELATION_METAPHOR;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_SEMANTIC_GRAPH: return HHS_EXACT_PASS219_LANGUAGE_RELATION_PATTERN;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_CONTEXT_DISCOURSE: return HHS_EXACT_PASS219_LANGUAGE_RELATION_DISCOURSE;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_AUDIO_LANGUAGE: return HHS_EXACT_PASS219_LANGUAGE_RELATION_AUDIO_TRANSCRIPTION;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_MODEL_PROPOSAL: return HHS_EXACT_PASS219_LANGUAGE_RELATION_MODEL_CANDIDATE;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_TOKENIZATION_INGESTION: return HHS_EXACT_PASS219_LANGUAGE_RELATION_OCCURRENCE_OF;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_VECTOR_HYDRATION: return HHS_EXACT_PASS219_LANGUAGE_RELATION_VECTOR_CANDIDATE;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_SYMBOLIC_TRANSLATION: return HHS_EXACT_PASS219_LANGUAGE_RELATION_SYMBOLIC_PROJECTION;
        default: return HHS_EXACT_PASS219_LANGUAGE_RELATION_PATTERN;
    }
}

static uint64_t flags_for(uint32_t layer) {
    uint64_t f = HHS_EXACT_PASS219_LANGUAGE_FLAG_NONAUTHORITATIVE | HHS_EXACT_PASS219_LANGUAGE_FLAG_EXACT_NO_FLOAT | HHS_EXACT_PASS219_LANGUAGE_FLAG_TYPED_RELATION | HHS_EXACT_PASS219_LANGUAGE_FLAG_PROVENANCE_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_REVERSIBLE_PROVENANCE;
    switch (layer) {
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_VERBATIM_SOURCE: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_VERBATIM_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_TOKEN_TENSOR: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_LEXEME_OCCURRENCE_SEPARATE | HHS_EXACT_PASS219_LANGUAGE_FLAG_ORDER_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_SCOPE_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_GRAMMAR_SYNTAX: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_GRAMMAR_ROLE_PRESENT | HHS_EXACT_PASS219_LANGUAGE_FLAG_ORDER_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_SCOPE_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_PROPOSITION: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_REFERENCE_IDENTITY_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_SCOPE_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_AMBIGUITY: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_AMBIGUITY_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_TRANSLATION_REGISTER: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_ORDER_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_SCOPE_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_METAPHOR_ANALOGY: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_PATTERN_RECOGNITION_EXPLICIT | HHS_EXACT_PASS219_LANGUAGE_FLAG_METAPHOR_DECLARED | HHS_EXACT_PASS219_LANGUAGE_FLAG_RECONSTRUCTION_MAP_PRESENT; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_CONTEXT_DISCOURSE: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_DISCOURSE_HISTORY_PRESENT | HHS_EXACT_PASS219_LANGUAGE_FLAG_SCOPE_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_AUDIO_LANGUAGE: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_REFERENCE_IDENTITY_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_MODEL_PROPOSAL: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_UNCERTAINTY_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_AMBIGUITY_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_TOKENIZATION_INGESTION: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_VERBATIM_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_LEXEME_OCCURRENCE_SEPARATE; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_SYMBOLIC_TRANSLATION: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_REFERENCE_IDENTITY_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_NEGATION_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_SCOPE_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_MODALITY_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_TEMPORALITY_PRESERVED | HHS_EXACT_PASS219_LANGUAGE_FLAG_UNCERTAINTY_PRESERVED; break;
        case HHS_EXACT_PASS219_LANGUAGE_LAYER_PATTERN_META_AWARENESS: f |= HHS_EXACT_PASS219_LANGUAGE_FLAG_PATTERN_RECOGNITION_EXPLICIT | HHS_EXACT_PASS219_LANGUAGE_FLAG_DISCOURSE_HISTORY_PRESENT; break;
        default: break;
    }
    return f;
}

static HHSExactPass219LanguageBindingV1 make_binding(uint32_t layer, const char source[HHS_EXACT_HASH72_STRLEN], uint32_t chars) {
    HHSExactPass219LanguageBindingV1 b;
    memset(&b, 0, sizeof(b));
    b.struct_size = (uint32_t)sizeof(b);
    b.version = hhs_exact_pass219_language_membrane_version();
    b.layer = layer;
    b.relation = relation_for(layer);
    b.invariant_flags = flags_for(layer);
    b.source_start = 0U;
    b.source_end = chars;
    b.occurrence_id = (layer == HHS_EXACT_PASS219_LANGUAGE_LAYER_TOKEN_TENSOR || layer == HHS_EXACT_PASS219_LANGUAGE_LAYER_TOKENIZATION_INGESTION) ? layer : HHS_EXACT_PASS219_LANGUAGE_NO_OCCURRENCE;
    b.relation_polarity = 1;
    memcpy(b.source_root_hash72, source, HHS_EXACT_HASH72_STRLEN);
    fill_hash(b.layer_root_hash72, HHS_EXACT_HASH72_ALPHABET[(layer + 1U) % HHS_EXACT_HASH72_LEN]);
    if (layer == HHS_EXACT_PASS219_LANGUAGE_LAYER_METAPHOR_ANALOGY) fill_hash(b.reconstruction_root_hash72, HHS_EXACT_HASH72_ALPHABET[17]);
    return b;
}

int main(void) {
    char source[HHS_EXACT_HASH72_STRLEN];
    HHSExactPass219LanguageMembraneV1 membrane;
    HHSExactPass219LanguageRNAProjectionV1 projection;
    HHSExactPass219RNAExecutionPlanV1 plan;
    uint32_t i;
    fill_hash(source, HHS_EXACT_HASH72_ALPHABET[0]);
    assert(hhs_exact_pass219_language_membrane_init(source, 128U, &membrane) == HHS_EXACT_STATUS_OK);
    for (i = 0U; i < HHS_EXACT_PASS219_LANGUAGE_MEMBRANE_LAYER_COUNT; ++i) {
        HHSExactPass219LanguageBindingV1 binding = make_binding(i, source, 128U);
        assert(hhs_exact_pass219_language_membrane_add(&membrane, &binding) == HHS_EXACT_STATUS_OK);
    }
    assert(membrane.layer_mask == HHS_EXACT_PASS219_LANGUAGE_MEMBRANE_FULL_LAYER_MASK);
    assert(hhs_exact_pass219_language_membrane_validate_complete(&membrane) == HHS_EXACT_STATUS_OK);
    memset(&plan, 0, sizeof(plan));
    plan.struct_size = (uint32_t)sizeof(plan);
    plan.version = hhs_exact_pass219_rna_execution_composer_version();
    plan.route = HHS_EXACT_PASS219_RNA_EXECUTION_ROUTE_INDEXED_CONTINUATION;
    assert(hhs_exact_pass219_language_membrane_project_rna_plan(&membrane, &plan, &projection) == HHS_EXACT_STATUS_OK);
    assert(projection.projection_only == 1U && projection.admission_required == 1U);
    assert(projection.authority_inherited_from_language == 0U && projection.vm81_mutation_authority_from_language == 0U && projection.hash72_mint_authority_from_language == 0U && projection.hash216_persistence_authority_from_language == 0U);
    { HHSExactPass219LanguageBindingV1 bad = make_binding(HHS_EXACT_PASS219_LANGUAGE_LAYER_LEXICAL_RELATION, source, 128U); bad.relation = HHS_EXACT_PASS219_LANGUAGE_RELATION_IDENTITY; assert(hhs_exact_pass219_language_binding_validate(&bad, 128U) == HHS_EXACT_STATUS_INVARIANT_FAILURE); }
    { HHSExactPass219LanguageBindingV1 bad = make_binding(HHS_EXACT_PASS219_LANGUAGE_LAYER_MODEL_PROPOSAL, source, 128U); bad.invariant_flags &= ~HHS_EXACT_PASS219_LANGUAGE_FLAG_NONAUTHORITATIVE; assert(hhs_exact_pass219_language_binding_validate(&bad, 128U) == HHS_EXACT_STATUS_INVARIANT_FAILURE); }
    { HHSExactPass219LanguageBindingV1 bad = make_binding(HHS_EXACT_PASS219_LANGUAGE_LAYER_METAPHOR_ANALOGY, source, 128U); bad.invariant_flags &= ~HHS_EXACT_PASS219_LANGUAGE_FLAG_METAPHOR_DECLARED; assert(hhs_exact_pass219_language_binding_validate(&bad, 128U) == HHS_EXACT_STATUS_INVARIANT_FAILURE); }
    { HHSExactPass219LanguageMembraneV1 bad = membrane; bad.hash72_mint_authority = 1U; assert(hhs_exact_pass219_language_membrane_validate(&bad) == HHS_EXACT_STATUS_INVARIANT_FAILURE); }
    return 0;
}
