"""Pass 219 diagnostic probe for Platonic multi-state fold closure.

This probe tests the smallest >2-state case without changing canonical authority.
Two validated disjoint RML5 u^36 chiral-pair involutions generate a four-state
mechanical orbit.  The I182 {3,3} Platonic closure independently requires
V=4, E=6, F=4 and q=3.  The probe tests whether the four orbit states admit
exact reversible translation on every pair, so their complete pair relation
has the tetrahedral K4 incidence counts.

This is diagnostic/read-only.  It does not turn the I182 incidence witness into
VM81 mutation authority, does not mint Hash72/Hash216, and does not collapse
ordered non-commutative product identity.
"""
from __future__ import annotations

from collections import Counter
from hashlib import sha256
from itertools import combinations
import json
from typing import Any, Mapping

from hhs_runtime.pass219.dynamic_octonion_gyroscope import (
    CHANNELS,
    PRODUCTS,
    build_gyroscope_state,
    expected_product_phase,
)
from hhs_runtime.pass219.gyroscope_admission_membrane import (
    build_chirality_polarity_witness,
    construct_admissible_reciprocal_path,
    flip_chiral_pair_half_turn,
)
from hhs_runtime.pass219.harmonic_geometry_circuit_i182 import Q_H, derive_platonic_closure

PASS = 219
ITERATION = "PLATONIC_MULTISTATE_FOLD_PROBE_1_0"
SCHEMA = "HHS_PASS219_PLATONIC_MULTISTATE_FOLD_PROBE_V1"
TETRAHEDRAL_PAIR = (3, 3)
STATE_ORDER = ("S00", "S10", "S01", "S11")


class PlatonicMultistateFoldProbeError(RuntimeError):
    pass


def _reject_float(value: Any, path: str = "$") -> None:
    if isinstance(value, float):
        raise PlatonicMultistateFoldProbeError(f"FLOAT_PROBE_AUTHORITY_FORBIDDEN:{path}")
    if isinstance(value, Mapping):
        for key, child in value.items():
            _reject_float(child, f"{path}.{key}")
    elif isinstance(value, (list, tuple)):
        for index, child in enumerate(value):
            _reject_float(child, f"{path}[{index}]")


def _canonical(value: Any) -> bytes:
    _reject_float(value)
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
        default=str,
    ).encode("utf-8")


def _digest(value: Any) -> str:
    return sha256(_canonical(value)).hexdigest()


def _source_state() -> dict[str, Any]:
    primitives = {"x": 7, "y": 19, "z": 31, "w": 43}
    signs = {"xy": 1, "yx": -1, "zw": 1, "wz": -1}
    phases = {
        "x": primitives["x"],
        "y": primitives["y"],
        "z": primitives["z"],
        "w": primitives["w"],
        "xy": expected_product_phase(primitives["x"], signs["xy"]),
        "yx": expected_product_phase(primitives["y"], signs["yx"]),
        "zw": expected_product_phase(primitives["z"], signs["zw"]),
        "wz": expected_product_phase(primitives["w"], signs["wz"]),
    }
    return build_gyroscope_state(phases, signs, state_id="platonic-fold:S00")


def _mechanical_key(state: Mapping[str, Any]) -> tuple[Any, ...]:
    phases = state.get("phases")
    signs = state.get("quarter_turn_signs")
    if not isinstance(phases, Mapping) or tuple(phases.keys()) != CHANNELS:
        raise PlatonicMultistateFoldProbeError("ORDERED_EIGHT_CHANNEL_STATE_REQUIRED")
    if not isinstance(signs, Mapping) or tuple(signs.keys()) != PRODUCTS:
        raise PlatonicMultistateFoldProbeError("ORDERED_PRODUCT_SIGN_STATE_REQUIRED")
    return (
        state.get("ambient_state_index"),
        tuple((channel, phases[channel]) for channel in CHANNELS),
        tuple((product, signs[product]) for product in PRODUCTS),
    )


def _mechanically_equal(left: Mapping[str, Any], right: Mapping[str, Any]) -> bool:
    return _mechanical_key(left) == _mechanical_key(right)


def build_four_state_chiral_orbit() -> dict[str, Any]:
    """Build the C2 x C2 mechanical orbit generated by the two disjoint pair flips."""
    s00 = _source_state()
    s10 = flip_chiral_pair_half_turn(
        s00,
        pair_index=0,
        transition_id="platonic-fold:g0",
    )["next_state"]
    s01 = flip_chiral_pair_half_turn(
        s00,
        pair_index=1,
        transition_id="platonic-fold:g1",
    )["next_state"]

    s11_01 = flip_chiral_pair_half_turn(
        s10,
        pair_index=1,
        transition_id="platonic-fold:g0:g1",
    )["next_state"]
    s11_10 = flip_chiral_pair_half_turn(
        s01,
        pair_index=0,
        transition_id="platonic-fold:g1:g0",
    )["next_state"]

    g0_back = flip_chiral_pair_half_turn(
        s10,
        pair_index=0,
        transition_id="platonic-fold:g0:back",
    )["next_state"]
    g1_back = flip_chiral_pair_half_turn(
        s01,
        pair_index=1,
        transition_id="platonic-fold:g1:back",
    )["next_state"]

    states = {"S00": s00, "S10": s10, "S01": s01, "S11": s11_01}
    unique_keys = {_mechanical_key(state) for state in states.values()}
    all_admissible = all(state.get("admissible_product_geometry") is True for state in states.values())
    all_balanced = all(
        build_chirality_polarity_witness(state)["all_chiral_pairs_opposed"] is True
        for state in states.values()
    )

    return {
        "states": states,
        "state_order": list(STATE_ORDER),
        "unique_mechanical_state_count": len(unique_keys),
        "g0_self_inverse": _mechanically_equal(g0_back, s00),
        "g1_self_inverse": _mechanically_equal(g1_back, s00),
        "disjoint_generators_commute_mechanically": _mechanically_equal(s11_01, s11_10),
        "receipt_ancestry_collapsed": False,
        "all_states_admissible": all_admissible,
        "all_states_balanced_chirality": all_balanced,
        "mechanical_orbit_signature": "C2_X_C2_DISJOINT_U36_FOLD_ORBIT",
    }


def tetrahedral_multistate_translation_probe() -> dict[str, Any]:
    """Test exact all-pairs translation across the four-state chiral orbit."""
    tetra = derive_platonic_closure(*TETRAHEDRAL_PAIR)
    tetra.verify()
    if (tetra.vertices, tetra.edges, tetra.faces, tetra.q) != (4, 6, 4, 3):
        raise PlatonicMultistateFoldProbeError("TETRAHEDRAL_CLOSURE_DRIFT")

    orbit = build_four_state_chiral_orbit()
    states = orbit["states"]
    if orbit["unique_mechanical_state_count"] != tetra.vertices:
        raise PlatonicMultistateFoldProbeError("FOUR_STATE_ORBIT_VERTEX_COUNT_MISMATCH")
    if orbit["disjoint_generators_commute_mechanically"] is not True:
        raise PlatonicMultistateFoldProbeError("DISJOINT_FOLD_GENERATORS_DID_NOT_COMMUTE")

    undirected_pairs = list(combinations(STATE_ORDER, 2))
    if len(undirected_pairs) != tetra.edges:
        raise PlatonicMultistateFoldProbeError("TETRAHEDRAL_EDGE_COUNT_MISMATCH")

    degree = Counter()
    directed_routes: list[dict[str, Any]] = []
    move_histogram: Counter[int] = Counter()
    for left, right in undirected_pairs:
        degree[left] += 1
        degree[right] += 1
        for source_label, target_label in ((left, right), (right, left)):
            path = construct_admissible_reciprocal_path(
                states[source_label],
                states[target_label],
                path_id=f"platonic-fold:{source_label}:{target_label}",
            )
            if path["target_reached_exactly"] is not True:
                raise PlatonicMultistateFoldProbeError("MULTISTATE_TARGET_NOT_REACHED")
            if path["all_moves_reversible"] is not True:
                raise PlatonicMultistateFoldProbeError("MULTISTATE_ROUTE_NOT_REVERSIBLE")
            if path["strong_connectivity_proven_for_rml5_balanced_chirality_manifold"] is not True:
                raise PlatonicMultistateFoldProbeError("MULTISTATE_STRONG_CONNECTIVITY_WITNESS_MISSING")
            if any(move["kind"] != "CHIRAL_PAIR_U36_FLIP" for move in path["moves"]):
                raise PlatonicMultistateFoldProbeError("PURE_CHIRAL_ORBIT_REQUIRED_COUPLED_GENERATOR_MOVE")
            move_histogram[path["move_count"]] += 1
            directed_routes.append(
                {
                    "source": source_label,
                    "target": target_label,
                    "move_count": path["move_count"],
                    "moves": [move["kind"] for move in path["moves"]],
                    "path_sha256": path["path_sha256"],
                    "target_reached_exactly": True,
                    "all_moves_reversible": True,
                }
            )

    faces = []
    edge_keys = {frozenset(pair) for pair in undirected_pairs}
    for face_vertices in combinations(STATE_ORDER, 3):
        face_edges = [frozenset(pair) for pair in combinations(face_vertices, 2)]
        if not all(edge in edge_keys for edge in face_edges):
            raise PlatonicMultistateFoldProbeError("TETRAHEDRAL_FACE_EDGE_CLOSURE_FAILED")
        faces.append(list(face_vertices))

    valence_matches = all(degree[label] == tetra.q for label in STATE_ORDER)
    euler_matches = len(STATE_ORDER) - len(undirected_pairs) + len(faces) == tetra.euler == 2
    expected_move_histogram = {1: 8, 2: 4}
    move_histogram_matches = dict(sorted(move_histogram.items())) == expected_move_histogram

    report = {
        "schema": SCHEMA,
        "pass": PASS,
        "iteration": ITERATION,
        "hydration_quantum": Q_H,
        "platonic_branch": {
            "p": tetra.p,
            "q": tetra.q,
            "vertices": tetra.vertices,
            "edges": tetra.edges,
            "faces": tetra.faces,
            "euler": tetra.euler,
        },
        "orbit": {
            "state_order": orbit["state_order"],
            "unique_mechanical_state_count": orbit["unique_mechanical_state_count"],
            "g0_self_inverse": orbit["g0_self_inverse"],
            "g1_self_inverse": orbit["g1_self_inverse"],
            "disjoint_generators_commute_mechanically": orbit[
                "disjoint_generators_commute_mechanically"
            ],
            "all_states_admissible": orbit["all_states_admissible"],
            "all_states_balanced_chirality": orbit["all_states_balanced_chirality"],
            "mechanical_orbit_signature": orbit["mechanical_orbit_signature"],
            "receipt_ancestry_collapsed": orbit["receipt_ancestry_collapsed"],
        },
        "translation": {
            "undirected_relation_count": len(undirected_pairs),
            "directed_translation_count": len(directed_routes),
            "directed_routes": directed_routes,
            "all_pairs_exactly_translatable": len(directed_routes) == 2 * tetra.edges,
            "all_routes_reversible": all(route["all_moves_reversible"] for route in directed_routes),
            "all_routes_use_only_existing_u36_fold_primitive": all(
                all(kind == "CHIRAL_PAIR_U36_FLIP" for kind in route["moves"])
                for route in directed_routes
            ),
            "move_count_histogram": dict(sorted(move_histogram.items())),
            "move_count_histogram_matches_two_generator_orbit": move_histogram_matches,
        },
        "incidence": {
            "degree_by_state": dict(sorted(degree.items())),
            "vertex_valence_matches_q3": valence_matches,
            "triangular_faces": faces,
            "face_count_matches": len(faces) == tetra.faces,
            "euler_closure_matches": euler_matches,
            "complete_pair_relation_is_tetrahedral_K4": (
                len(STATE_ORDER) == 4
                and len(undirected_pairs) == 6
                and valence_matches
                and len(faces) == 4
                and euler_matches
            ),
        },
        "primitive_result": {
            "new_local_fold_primitive_required": False,
            "two_commuting_order2_u36_generators_create_four_state_orbit": True,
            "platonic_incidence_lifts_pairwise_folds_to_multistate_relation": True,
            "two_fold_diagonals_exist": move_histogram[2] == 4,
            "two_fold_diagonals_are_superedge_candidates_only": True,
            "more_than_two_states_entangled_in_one_incidence_closure": tetra.vertices > 2,
        },
        "authority": {
            "diagnostic_only": True,
            "canonical_geometry_mutation": False,
            "vm81_mutation": False,
            "hash72_minting": False,
            "hash216_persistence": False,
            "floating_point_authority": False,
            "ordered_product_collapse": False,
        },
    }
    report["report_sha256"] = _digest(report)
    return report


def main() -> int:
    report = tetrahedral_multistate_translation_probe()
    required = (
        report["orbit"]["g0_self_inverse"],
        report["orbit"]["g1_self_inverse"],
        report["orbit"]["disjoint_generators_commute_mechanically"],
        report["orbit"]["all_states_admissible"],
        report["translation"]["all_pairs_exactly_translatable"],
        report["translation"]["all_routes_reversible"],
        report["translation"]["all_routes_use_only_existing_u36_fold_primitive"],
        report["translation"]["move_count_histogram_matches_two_generator_orbit"],
        report["incidence"]["complete_pair_relation_is_tetrahedral_K4"],
        report["primitive_result"]["more_than_two_states_entangled_in_one_incidence_closure"],
    )
    print(json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False))
    return 0 if all(required) else 1


if __name__ == "__main__":
    raise SystemExit(main())
