[Unit]
Requires=hhs-dns-gate-resolved.service
After=hhs-dns-gate-resolved.service

[Service]
ExecStart=
ExecStart=/opt/hhs/venv/bin/python -m uvicorn hhs_backend.visual_server:app --host 127.196.0.1 --port 8080 --workers 1
