#!/usr/bin/env python3
"""Normalize the HHS production service boundary before guarded promotion.

The primary responsibility remains checkout read/traverse permissions. A narrow
runtime-state boundary also normalizes only the canonical unified Hash72 ledger
directory, snapshot, and journal to the configured service group so the service
can read and append after a root-owned recovery operation.

A separate fail-closed recovery hook repairs *only* derivable unified Hash72
journal transition metadata when all of the following are true:

* the authoritative ledger entry chain independently verifies;
* the ledger verifier reports only transition-metadata mismatches;
* guarded-update receipts terminate in ``ROLLBACK_HEALTH_FAILED``; and
* no production listener remains after hhs.service is stopped.

That hook exists because this tool executes before the guarded installer's
pre-promotion health gate, including rollback recovery. It never repairs entry
payloads/hashes or snapshot authority and emits an out-of-ledger backup/receipt.
Git-tracked source plus the canonical generated native runtime library boundary
are normalized; unrelated untracked host state and secrets remain untouched.
"""
from __future__ import annotations

import argparse
import grp
import json
import os
from pathlib import Path
import pwd
import stat
import subprocess
import sys
import time
from typing import Any


def _tracked_paths(root: Path) -> tuple[Path, ...]:
    result = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z"],
        check=True,
        capture_output=True,
    )
    return tuple(
        root / Path(raw.decode("utf-8", errors="strict"))
        for raw in result.stdout.split(b"\0")
        if raw
    )


def _set_group_mode(
    path: Path,
    gid: int,
    *,
    directory: bool,
    allow_chown: bool,
    writable: bool = False,
) -> None:
    if not path.exists() or path.is_symlink():
        return
    current = path.stat()
    if allow_chown:
        os.chown(path, -1, gid)
    required = stat.S_IRGRP | (stat.S_IXGRP if directory else 0)
    if writable:
        required |= stat.S_IWGRP
    desired = stat.S_IMODE(current.st_mode) | required
    if desired != stat.S_IMODE(current.st_mode):
        os.chmod(path, desired)


def _identity_group_ids(user: str) -> tuple[int, frozenset[int]]:
    """Resolve service identity without spawning a privileged PAM helper."""

    identity = pwd.getpwnam(user)
    gids = {identity.pw_gid}
    for group in grp.getgrall():
        if user in group.gr_mem:
            gids.add(group.gr_gid)
    return identity.pw_uid, frozenset(gids)


def _service_access(user: str, path: Path, flag: str) -> bool:
    if flag not in {"-x", "-r", "-w"}:
        raise ValueError(f"unsupported service access flag: {flag}")

    uid, gids = _identity_group_ids(user)
    current = path.stat()
    mode = stat.S_IMODE(current.st_mode)

    owner_bits = {"-x": stat.S_IXUSR, "-r": stat.S_IRUSR, "-w": stat.S_IWUSR}
    group_bits = {"-x": stat.S_IXGRP, "-r": stat.S_IRGRP, "-w": stat.S_IWGRP}
    other_bits = {"-x": stat.S_IXOTH, "-r": stat.S_IROTH, "-w": stat.S_IWOTH}
    if current.st_uid == uid:
        required = owner_bits[flag]
    elif current.st_gid in gids:
        required = group_bits[flag]
    else:
        required = other_bits[flag]
    return bool(mode & required)


def normalize_checkout(
    root: Path,
    *,
    service_user: str,
    service_group: str,
    require_root: bool = True,
) -> dict[str, Any]:
    root = root.resolve()
    if require_root and os.geteuid() != 0:
        raise PermissionError("production permission normalization requires root")
    if not (root / ".git").exists():
        raise FileNotFoundError(f"repository missing at {root}")

    user = pwd.getpwnam(service_user)
    group = grp.getgrnam(service_group)
    gid = group.gr_gid
    allow_chown = os.geteuid() == 0

    tracked = _tracked_paths(root)
    tracked_files = 0
    tracked_dirs: set[Path] = {root, root.parent}

    for path in tracked:
        if not path.exists() or path.is_symlink():
            continue
        if path.is_dir():
            tracked_dirs.add(path)
            continue
        _set_group_mode(path, gid, directory=False, allow_chown=allow_chown)
        tracked_files += 1
        parent = path.parent
        while parent == root or root in parent.parents:
            tracked_dirs.add(parent)
            if parent == root:
                break
            parent = parent.parent

    # /opt/hhs and /opt/hhs/app are normalized to the service group.
    # /opt itself remains host/root-owned and is verified, not chowned.
    for directory in sorted(tracked_dirs, key=lambda value: len(value.parts)):
        _set_group_mode(directory, gid, directory=True, allow_chown=allow_chown)

    # The native shared object is generated by `make c-abi`, so it is normally
    # Git-untracked. It is nevertheless part of the canonical service runtime
    # boundary and must remain readable during rollback/recovery before a new
    # build can run. Normalize only this exact generated path; do not recurse
    # through any other untracked file or directory.
    runtime_build_dir = root / "hhs_runtime" / "builds"
    runtime_library = runtime_build_dir / "libhhs_runtime.so"
    runtime_library_present = runtime_library.is_file() and not runtime_library.is_symlink()
    if runtime_library_present:
        _set_group_mode(runtime_build_dir, gid, directory=True, allow_chown=allow_chown)
        _set_group_mode(runtime_library, gid, directory=False, allow_chown=allow_chown)

    backend = root / "hhs_backend"
    init_file = backend / "__init__.py"
    required_dirs = (root.parent.parent, root.parent, root, backend)
    for directory in required_dirs:
        if not directory.is_dir():
            raise FileNotFoundError(f"required production directory missing: {directory}")
        if not _service_access(service_user, directory, "-x"):
            raise PermissionError(
                f"service user {service_user} cannot traverse {directory}"
            )
    if not init_file.is_file():
        raise FileNotFoundError(f"required backend package marker missing: {init_file}")
    if not _service_access(service_user, init_file, "-r"):
        raise PermissionError(
            f"service user {service_user} cannot read {init_file}"
        )

    runtime_library_readable: bool | None = None
    if runtime_library_present:
        if not _service_access(service_user, runtime_build_dir, "-x"):
            raise PermissionError(
                f"service user {service_user} cannot traverse {runtime_build_dir}"
            )
        runtime_library_readable = _service_access(service_user, runtime_library, "-r")
        if not runtime_library_readable:
            raise PermissionError(
                f"service user {service_user} cannot read {runtime_library}"
            )

    return {
        "schema": "HHS_PRODUCTION_CHECKOUT_PERMISSION_RECEIPT_V2",
        "repository_root": str(root),
        "service_user": user.pw_name,
        "service_group": group.gr_name,
        "tracked_files_normalized": tracked_files,
        "tracked_directories_normalized": len(tracked_dirs),
        "backend_init_readable": True,
        "parent_traversal_verified": [str(path) for path in required_dirs],
        "service_access_verification": "mode-bits-with-resolved-supplementary-groups",
        "runtime_library_path": str(runtime_library),
        "runtime_library_present": runtime_library_present,
        "runtime_library_readable": runtime_library_readable,
        "untracked_runtime_permission_boundary": (
            [str(runtime_build_dir), str(runtime_library)] if runtime_library_present else []
        ),
        "untracked_runtime_permissions_normalized": runtime_library_present,
        "untracked_state_modified": False,
        "result": "PASS",
    }


def normalize_unified_ledger_permissions(
    runtime_output_dir: Path,
    *,
    service_user: str,
    service_group: str,
    require_root: bool = True,
) -> dict[str, Any]:
    """Normalize only the canonical unified-ledger service permission surface."""

    runtime_output_dir = runtime_output_dir.resolve()
    if require_root and os.geteuid() != 0:
        raise PermissionError("runtime ledger permission normalization requires root")
    if not runtime_output_dir.is_dir():
        return {
            "schema": "HHS_PRODUCTION_UNIFIED_LEDGER_PERMISSION_RECEIPT_V1",
            "status": "NO_RUNTIME_OUTPUT_DIR",
            "runtime_output_dir": str(runtime_output_dir),
            "result": "PASS",
        }

    user = pwd.getpwnam(service_user)
    group = grp.getgrnam(service_group)
    gid = group.gr_gid
    allow_chown = os.geteuid() == 0
    ledger_path = runtime_output_dir / "hhs_unified_hash72_ledger.json"
    journal_path = Path(f"{ledger_path}.journal.jsonl")

    candidates: list[tuple[Path, bool]] = [(runtime_output_dir, True)]
    if ledger_path.exists():
        candidates.append((ledger_path, False))
    if journal_path.exists():
        candidates.append((journal_path, False))

    changed: list[str] = []
    for path, directory in candidates:
        if path.is_symlink():
            raise RuntimeError(f"refusing symlink in unified ledger permission boundary: {path}")
        before = path.stat()
        before_identity = (before.st_gid, stat.S_IMODE(before.st_mode))
        _set_group_mode(
            path,
            gid,
            directory=directory,
            allow_chown=allow_chown,
            writable=True,
        )
        after = path.stat()
        after_identity = (after.st_gid, stat.S_IMODE(after.st_mode))
        if after_identity != before_identity:
            changed.append(str(path))

    if not _service_access(service_user, runtime_output_dir, "-x"):
        raise PermissionError(f"service user {service_user} cannot traverse {runtime_output_dir}")
    if not _service_access(service_user, runtime_output_dir, "-w"):
        raise PermissionError(f"service user {service_user} cannot write {runtime_output_dir}")
    for path in (ledger_path, journal_path):
        if not path.exists():
            continue
        if not _service_access(service_user, path, "-r"):
            raise PermissionError(f"service user {service_user} cannot read {path}")
        if not _service_access(service_user, path, "-w"):
            raise PermissionError(f"service user {service_user} cannot write {path}")

    return {
        "schema": "HHS_PRODUCTION_UNIFIED_LEDGER_PERMISSION_RECEIPT_V1",
        "status": "NORMALIZED",
        "runtime_output_dir": str(runtime_output_dir),
        "ledger_path": str(ledger_path),
        "journal_path": str(journal_path),
        "service_user": user.pw_name,
        "service_group": group.gr_name,
        "changed_paths": changed,
        "normalized_paths": [str(path) for path, _ in candidates],
        "service_read_write_verified": True,
        "result": "PASS",
    }


def _terminal_guarded_update_receipt(state_root: Path) -> dict[str, Any] | None:
    path = state_root / "receipts.jsonl"
    if not path.is_file():
        return None
    terminal: dict[str, Any] | None = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict):
            terminal = parsed
    return terminal


def _production_listener_present() -> bool:
    result = subprocess.run(
        ["ss", "-H", "-ltn", "sport = :8080"],
        check=False,
        capture_output=True,
        text=True,
    )
    return bool(result.stdout.strip())


def _stop_production_service_and_verify_quiescent() -> None:
    subprocess.run(["systemctl", "stop", "hhs.service"], check=False)
    deadline = time.monotonic() + 20.0
    while time.monotonic() < deadline:
        if not _production_listener_present():
            return
        time.sleep(0.25)
    raise RuntimeError("refusing ledger recovery while production port 8080 still has a listener")


def recover_unified_ledger_rollback_boundary(
    root: Path,
    *,
    state_root: Path = Path("/var/lib/hhs-guarded-update"),
    runtime_output_dir: Path = Path("/var/lib/hhs/data/runtime"),
) -> dict[str, Any]:
    """Repair transition-only ledger corruption after a proven failed rollback.

    The candidate recovery implementation is loaded from the guarded-update
    source worktree, while HHS_REPO_ROOT remains bound to the live checkout so
    the already-built canonical native Hash72 runtime remains authoritative.
    """

    ledger_path = runtime_output_dir / "hhs_unified_hash72_ledger.json"
    if not ledger_path.is_file():
        return {
            "schema": "HHS_PRODUCTION_UNIFIED_LEDGER_RECOVERY_BOUNDARY_V1",
            "status": "NO_LEDGER_PRESENT",
            "ledger_path": str(ledger_path),
            "result": "PASS",
        }

    source_root = Path(__file__).resolve().parents[3]
    if str(source_root) not in sys.path:
        sys.path.insert(0, str(source_root))
    os.environ["HHS_REPO_ROOT"] = str(root.resolve())
    os.environ.setdefault("HHS_RUNTIME_OUTPUT_DIR", str(runtime_output_dir))

    from hhs_runtime.hhs_unified_hash72_ledger_recovery_v1 import (  # noqa: PLC0415
        inspect_transition_metadata_recovery,
        repair_transition_metadata,
    )

    inspection = inspect_transition_metadata_recovery(ledger_path)
    if inspection.get("status") == "VALID_NO_REPAIR_REQUIRED":
        return {
            "schema": "HHS_PRODUCTION_UNIFIED_LEDGER_RECOVERY_BOUNDARY_V1",
            "status": "LEDGER_VALID",
            "ledger_path": str(ledger_path),
            "result": "PASS",
        }

    terminal = _terminal_guarded_update_receipt(state_root)
    if not terminal or terminal.get("outcome") != "ROLLBACK_HEALTH_FAILED":
        raise RuntimeError(
            "recoverable unified ledger corruption requires terminal "
            f"ROLLBACK_HEALTH_FAILED receipt, found {terminal}"
        )

    _stop_production_service_and_verify_quiescent()
    recovery_root = state_root / "unified-ledger-recovery"
    repaired = repair_transition_metadata(
        ledger_path,
        backup_root=recovery_root,
        require_repair=True,
    )

    subprocess.run(["systemctl", "reset-failed", "hhs.service"], check=False)
    subprocess.run(["systemctl", "start", "hhs.service"], check=True)
    return {
        "schema": "HHS_PRODUCTION_UNIFIED_LEDGER_RECOVERY_BOUNDARY_V1",
        "status": "TRANSITION_METADATA_REPAIRED",
        "terminal_guarded_update_outcome": terminal.get("outcome"),
        "ledger_path": str(ledger_path),
        "recovery_receipt_path": repaired.get("receipt_path"),
        "backup_directory": repaired.get("backup_directory"),
        "entry_count": repaired.get("entry_count"),
        "ledger_hash72": repaired.get("ledger_hash72"),
        "tip_hash72": repaired.get("tip_hash72"),
        "journal_metadata_preserved": repaired.get("journal_metadata_preserved"),
        "service_restart_requested": True,
        "result": "PASS",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default="/opt/hhs/app")
    parser.add_argument("--service-user", default="hhs")
    parser.add_argument("--service-group", default="hhs")
    args = parser.parse_args()
    root = Path(args.repo_root)
    runtime_output_dir = Path(os.environ.get("HHS_RUNTIME_OUTPUT_DIR", "/var/lib/hhs/data/runtime"))

    receipt = normalize_checkout(
        root,
        service_user=args.service_user,
        service_group=args.service_group,
        require_root=True,
    )
    print(json.dumps(receipt, sort_keys=True))
    print("HHS_PRODUCTION_CHECKOUT_PERMISSIONS_VERIFIED=1")

    ledger_permissions_before = normalize_unified_ledger_permissions(
        runtime_output_dir,
        service_user=args.service_user,
        service_group=args.service_group,
        require_root=True,
    )
    print(json.dumps(ledger_permissions_before, sort_keys=True))
    print("HHS_PRODUCTION_UNIFIED_LEDGER_PERMISSIONS_VERIFIED=1")

    recovery = recover_unified_ledger_rollback_boundary(
        root,
        state_root=Path(os.environ.get("HHS_UPDATE_STATE_ROOT", "/var/lib/hhs-guarded-update")),
        runtime_output_dir=runtime_output_dir,
    )
    print(json.dumps(recovery, sort_keys=True, default=str))
    if recovery.get("status") == "TRANSITION_METADATA_REPAIRED":
        print("HHS_PRODUCTION_UNIFIED_LEDGER_RECOVERY_VERIFIED=1")
    else:
        print("HHS_PRODUCTION_UNIFIED_LEDGER_BOUNDARY_VALID=1")

    ledger_permissions_after = normalize_unified_ledger_permissions(
        runtime_output_dir,
        service_user=args.service_user,
        service_group=args.service_group,
        require_root=True,
    )
    print(json.dumps(ledger_permissions_after, sort_keys=True))
    print("HHS_PRODUCTION_UNIFIED_LEDGER_SERVICE_RW_VERIFIED=1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
