#ifndef HHS_GFCC_GEOMETRY_H
#define HHS_GFCC_GEOMETRY_H
#include "hhs_gfcc.h"

#define HHS_GFCC_GEOMETRY_FIXED_POINT_FRACTION_BITS 16u
#define HHS_GFCC_GEOMETRY_GOLDEN_AND_DYADIC_INDEPENDENT 1u

#endif
