const api='/api/pass153';
let state={status:null,session:null};
async function request(path,options={}){const response=await fetch(api+path,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(JSON.stringify(data));return data}
function show(id){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.panel));
async function refresh(){state.status=await request('/status');document.getElementById('system-status').textContent='Online · model outputs advisory';document.getElementById('dashboard-data').textContent=JSON.stringify(state.status,null,2);document.getElementById('model-list').innerHTML=state.status.models.map(m=>`<div class="card"><b>${m.model_id}</b><br>${m.backend}<br>${m.model_index.slice(0,24)}…</div>`).join('');document.getElementById('tool-list').innerHTML=state.status.tools.map(t=>`<div class="card"><b>${t.name}</b><br>${t.description}<br>Capability: ${t.required_capability}</div>`).join('');document.getElementById('session-list').textContent=JSON.stringify(state.status.sessions,null,2);const select=document.getElementById('agent-session');select.innerHTML=state.status.sessions.map(s=>`<option value="${s.session_id}">${s.session_id}</option>`).join('');if(!state.session&&state.status.sessions[0])state.session=state.status.sessions[0].session_id}
document.getElementById('create-session').onclick=async()=>{const s=await request('/sessions',{method:'POST',body:JSON.stringify({model_id:'hhs-reference-open-model-v1'})});state.session=s.session_id;await refresh()};
document.getElementById('send').onclick=async()=>{const id=document.getElementById('agent-session').value||state.session;if(!id)return;const data=await request(`/sessions/${id}/chat`,{method:'POST',body:JSON.stringify({prompt:document.getElementById('prompt').value,max_tokens:64})});document.getElementById('chat-output').textContent=JSON.stringify(data,null,2);await refresh()};
document.getElementById('replay').onclick=async()=>{const id=document.getElementById('agent-session').value||state.session;if(id)document.getElementById('replay-output').textContent=JSON.stringify(await request(`/sessions/${id}/replay`),null,2)};
refresh().catch(e=>document.getElementById('system-status').textContent=e.message);
