From Coq Require Import QArith QArith_base Ring Field List Bool Lra.
Import ListNotations.
Open Scope Q_scope.

(** HHS-GFE-FORMAL-136
    Exact polynomial contract for one admitted nonzero rational state alpha.
    No floating-point semantics occur in this file. *)

Inductive Var : Type := G | H | Rho.
Definition valuation := Var -> Q.

Inductive poly : Type :=
| C : Q -> poly
| X : Var -> poly
| Add : poly -> poly -> poly
| Mul : poly -> poly -> poly
| Neg : poly -> poly.

Declare Scope poly_scope.
Delimit Scope poly_scope with P.
Bind Scope poly_scope with poly.
Notation "0" := (C 0) : poly_scope.
Notation "1" := (C 1) : poly_scope.
Infix "+" := Add : poly_scope.
Infix "*" := Mul : poly_scope.
Notation "- p" := (Neg p) : poly_scope.
Notation "p - q" := (Add p (Neg q)) : poly_scope.

Fixpoint eval (v : valuation) (p : poly) : Q :=
  match p with
  | C q => q
  | X x => v x
  | Add p q => eval v p + eval v q
  | Mul p q => eval v p * eval v q
  | Neg p => - eval v p
  end.

Definition peq (p q : poly) : Prop := forall v, eval v p = eval v q.
Infix "==p" := peq (at level 70).

Lemma peq_refl : forall p, p ==p p.
Proof. firstorder. Qed.
Lemma peq_sym : forall p q, p ==p q -> q ==p p.
Proof. firstorder. Qed.
Lemma peq_trans : forall p q r, p ==p q -> q ==p r -> p ==p r.
Proof. firstorder. Qed.

Definition g : poly := X G.
Definition h : poly := X H.
Definition rho : poly := X Rho.

Definition qinv (a : Q) : Q := / a.
Definition rho_at (a : Q) : Q := a + / a - 2.

Definition reciprocal_constraint : poly := (g * h - 1)%P.
Definition residual_constraint : poly := (rho - g - h + C 2)%P.

Definition state_g (a : Q) : poly := (g - C a)%P.
Definition state_h (a : Q) : poly := (h - C (/a))%P.
Definition state_rho (a : Q) : poly := (rho - C (rho_at a))%P.

(** Ideal generated by the three state equations, represented by an explicit
    polynomial combination certificate. *)
Definition StateIdeal (a : Q) (p : poly) : Prop :=
  exists A B D : poly,
    p ==p (A * state_g a + B * state_h a + D * state_rho a)%P.

Lemma StateIdeal_zero : forall a, StateIdeal a 0%P.
Proof.
  intro a. exists 0%P, 0%P, 0%P. intro v. simpl. ring.
Qed.

Lemma StateIdeal_add : forall a p q,
  StateIdeal a p -> StateIdeal a q -> StateIdeal a (p + q)%P.
Proof.
  intros a p q [A [B [D Hp]]] [A' [B' [D' Hq]]].
  exists (A+A')%P, (B+B')%P, (D+D')%P.
  intro v. specialize (Hp v). specialize (Hq v). simpl in *. ring_simplify in *. lra.
Qed.

Lemma StateIdeal_mul_left : forall a p q,
  StateIdeal a p -> StateIdeal a (q * p)%P.
Proof.
  intros a p q [A [B [D Hp]]].
  exists (q*A)%P, (q*B)%P, (q*D)%P.
  intro v. specialize (Hp v). simpl in *. rewrite Hp. ring.
Qed.

(** The generic reciprocal equation belongs to every admitted nonzero state
    ideal.  Certificate:
      gh-1 = h(g-a) + a(h-a^-1). *)
Theorem reciprocal_constraint_in_state_ideal :
  forall a, a <> 0 -> StateIdeal a reciprocal_constraint.
Proof.
  intros a Ha.
  exists h, (C a), 0%P.
  intro v. unfold reciprocal_constraint, state_g, state_h.
  simpl. field_simpl; ring.
Qed.

(** The generic residual equation belongs to the state ideal.  Certificate:
      rho-g-h+2 = (rho-rho_a) -(g-a) -(h-a^-1). *)
Theorem residual_constraint_in_state_ideal :
  forall a, a <> 0 -> StateIdeal a residual_constraint.
Proof.
  intros a Ha.
  exists (C (-1)), (C (-1)), 1%P.
  intro v. unfold residual_constraint, state_g, state_h, state_rho, rho_at.
  simpl. field_simpl; ring.
Qed.

(** Explicit Buchberger S-polynomial certificates for the monic linear basis.
    With lex G > H > Rho the leading monomials are pairwise coprime. *)
Definition S_gh (a : Q) : poly :=
  (h * state_g a - g * state_h a)%P.
Definition S_gr (a : Q) : poly :=
  (rho * state_g a - g * state_rho a)%P.
Definition S_hr (a : Q) : poly :=
  (rho * state_h a - h * state_rho a)%P.

Theorem S_gh_reduces_to_zero : forall a, a <> 0 -> StateIdeal a (S_gh a).
Proof.
  intros a Ha.
  exists (C (/a)), (C (-a)), 0%P.
  intro v. unfold S_gh, state_g, state_h. simpl.
  field_simpl; ring.
Qed.

Theorem S_gr_reduces_to_zero : forall a, a <> 0 -> StateIdeal a (S_gr a).
Proof.
  intros a Ha.
  exists (C (rho_at a)), 0%P, (C (-a)).
  intro v. unfold S_gr, state_g, state_rho, rho_at. simpl.
  field_simpl; ring.
Qed.

Theorem S_hr_reduces_to_zero : forall a, a <> 0 -> StateIdeal a (S_hr a).
Proof.
  intros a Ha.
  exists 0%P, (C (rho_at a)), (C (-(/a))).
  intro v. unfold S_hr, state_h, state_rho, rho_at. simpl.
  field_simpl; ring.
Qed.

Record GroebnerCertificate (a : Q) : Prop := {
  gb_alpha_nonzero : a <> 0;
  gb_generic_reciprocal : StateIdeal a reciprocal_constraint;
  gb_generic_residual : StateIdeal a residual_constraint;
  gb_S_gh : StateIdeal a (S_gh a);
  gb_S_gr : StateIdeal a (S_gr a);
  gb_S_hr : StateIdeal a (S_hr a)
}.

Theorem groebner_basis_verification :
  forall a, a <> 0 -> GroebnerCertificate a.
Proof.
  intros a Ha. constructor; auto using reciprocal_constraint_in_state_ideal,
    residual_constraint_in_state_ideal, S_gh_reduces_to_zero,
    S_gr_reduces_to_zero, S_hr_reduces_to_zero.
Qed.

(** Canonical state valuation and Gröbner normal form. *)
Definition state_valuation (a : Q) : valuation :=
  fun x => match x with
           | G => a
           | H => /a
           | Rho => rho_at a
           end.

Definition nf (a : Q) (p : poly) : Q := eval (state_valuation a) p.
Definition quotient_equiv (a : Q) (p q : poly) : Prop := nf a p = nf a q.

Lemma generator_nf_zero : forall a,
  nf a (state_g a) = 0 /\
  nf a (state_h a) = 0 /\
  nf a (state_rho a) = 0.
Proof.
  intro a. unfold nf, state_valuation, state_g, state_h, state_rho. simpl.
  repeat split; ring.
Qed.

Lemma ideal_elements_nf_zero : forall a p,
  StateIdeal a p -> nf a p = 0.
Proof.
  intros a p [A [B [D Hp]]].
  unfold nf. specialize (Hp (state_valuation a)).
  simpl in Hp. unfold state_valuation, rho_at in Hp. simpl in Hp.
  field_simpl in Hp; lra.
Qed.

(** The executable quotient carrier is the set of certified Gröbner normal
    forms.  Because the basis fixes every variable, those normal forms are
    exactly constants in Q. *)
Record StateQuotient (a : Q) : Type := {
  quotient_nf : Q
}.

Definition quotient_add {a} (x y : StateQuotient a) : StateQuotient a :=
  {| quotient_nf := quotient_nf _ x + quotient_nf _ y |}.
Definition quotient_mul {a} (x y : StateQuotient a) : StateQuotient a :=
  {| quotient_nf := quotient_nf _ x * quotient_nf _ y |}.
Definition quotient_neg {a} (x : StateQuotient a) : StateQuotient a :=
  {| quotient_nf := - quotient_nf _ x |}.
Definition quotient_inv {a} (x : StateQuotient a) : StateQuotient a :=
  {| quotient_nf := / quotient_nf _ x |}.

Definition quotient_to_Q {a} (x : StateQuotient a) : Q := quotient_nf _ x.
Definition Q_to_quotient (a : Q) (q : Q) : StateQuotient a :=
  {| quotient_nf := q |}.

Record FieldIsomorphism (A B : Type) := {
  iso_to : A -> B;
  iso_from : B -> A;
  iso_to_from : forall b, iso_to (iso_from b) = b;
  iso_from_to : forall a, iso_from (iso_to a) = a
}.

Lemma StateQuotient_ext : forall a (x y : StateQuotient a),
  quotient_nf _ x = quotient_nf _ y -> x = y.
Proof.
  intros a [x] [y] H. simpl in H. subst. reflexivity.
Qed.

(** Requested theorem.  This theorem is intentionally for the instantiated
    maximal state ideal, not the generic reciprocal ideal. *)
Theorem quotient_isomorphic_to_field :
  forall a, a <> 0 -> FieldIsomorphism (StateQuotient a) Q.
Proof.
  intros a Ha.
  refine {| iso_to := quotient_to_Q;
            iso_from := Q_to_quotient a |}.
  - intro q. reflexivity.
  - intros [q]. reflexivity.
Qed.

(** Calibration theorem for alpha=5/4. *)
Theorem calibration_5_4 :
  nf (5#4) reciprocal_constraint = 0 /\
  nf (5#4) residual_constraint = 0 /\
  rho_at (5#4) = (1#20).
Proof.
  unfold nf, reciprocal_constraint, residual_constraint, state_valuation, rho_at.
  simpl. repeat split; vm_compute; reflexivity.
Qed.
