#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { TERMINAL_CLASSIFICATION, PASS160_BINDING } from '../src/finalization.mjs';
const root=resolve(new URL('..',import.meta.url).pathname), evidence=resolve(root,'evidence/pass161'); mkdirSync(evidence,{recursive:true});
const x=JSON.parse(readFileSync(process.env.P161_X86_REPORT,'utf8')); const a=JSON.parse(readFileSync(process.env.P161_ARM_REPORT,'utf8'));
const checks={x86_failures_zero:x.failures===0,arm_failures_zero:a.failures===0,replay_equal:x.replay_root===a.replay_root,source_equal:x.source_root===a.source_root,pass160_root_bound:x.inherited_pass160_closure_root===PASS160_BINDING.main_closure_root&&a.inherited_pass160_closure_root===PASS160_BINDING.main_closure_root,native_bound:x.native_pass160_bound===true&&a.native_pass160_bound===true,browser_complete:x.browser_checks===x.browser_checks_passed&&a.browser_checks===a.browser_checks_passed,plugin_contained:x.plugin_containment===true&&a.plugin_containment===true};
const omega=Object.values(checks).every(Boolean); const packagePath=resolve(root,'HHS_PASS_161_RELEASE_BUNDLE.json'); const pkg=JSON.parse(readFileSync(packagePath,'utf8'));
const receipt={schema:'P161_COMPLETION_RECEIPT_V1',contract:'HHS-P161-HHUMOCE',classification:omega?TERMINAL_CLASSIFICATION:'HHS_PASS_161_IMPLEMENTATION_ACTIVE_PENDING_FULL_CLOSURE',omega_161:omega,terminal_claimed:omega,checks,replay_root:x.replay_root,source_manifest_root:x.source_root,pass160_main_closure_root:PASS160_BINDING.main_closure_root,release_bundle_sha256:pkg.archive_sha256,bounded_final_gate_count:1,validation_failures:Object.values(checks).filter((v)=>!v).length};
writeFileSync(resolve(evidence,'P161_COMPLETION_RECEIPT.json'),JSON.stringify(receipt,null,2)+'\n'); const receiptHash=createHash('sha256').update(readFileSync(resolve(evidence,'P161_COMPLETION_RECEIPT.json'))).digest('hex');
const closure={schema:'P161_TERMINAL_CLOSURE_V1',classification:receipt.classification,omega_161:receipt.omega_161,terminal_claimed:receipt.terminal_claimed,completion_receipt_sha256:receiptHash,release_bundle_sha256:pkg.archive_sha256,replay_root:receipt.replay_root,valid:omega}; writeFileSync(resolve(evidence,'P161_TERMINAL_CLOSURE.json'),JSON.stringify(closure,null,2)+'\n'); writeFileSync(resolve(evidence,'P161_TERMINAL_CLASSIFICATION.txt'),(omega?TERMINAL_CLASSIFICATION:'PENDING')+'\n');
const terminal={schema:'HHS_PASS_161_TERMINAL_RELEASE_V1',contract:'HHS-P161-HHUMOCE',classification:receipt.classification,omega_161:omega,terminal_claimed:omega,completion_receipt_sha256:receiptHash,release_bundle_sha256:pkg.archive_sha256,release_bundle_bytes:statSync(resolve(root,pkg.archive)).size,replay_root:receipt.replay_root,pass160_main_closure_root:PASS160_BINDING.main_closure_root}; writeFileSync(resolve(root,'HHS_PASS_161_TERMINAL_RELEASE.json'),JSON.stringify(terminal,null,2)+'\n'); console.log(JSON.stringify(receipt)); if(!omega) process.exit(1);
